### ISSUE TITLE
Inputs and Output in KKRT Protocol

### ISSUE THREAD

**Issue by barryallen94** [osu-crypto/libOTe#10]
I would like to use KKRT implementation of the libOTe library. For using KKRT protocol, previous issues have been directed to https://github.com/osu-crypto/libOTe/blob/master/libOTe_Tests/NcoOT_Tests.cpp#L32. Here, which method/function should we follow? Further, I am unable to figure out for each N choose 1 OTs which object stores the random inputs of the Sender and the choices and the inputs received corresponding to the choices for the Receiver.  Can you direct me to these objects?

**Comment by ladnir** [comment]
This is a question, not an issue... See the documentation here

https://github.com/osu-crypto/libOTe/blob/master/libOTe/NChooseOne/NcoOtExt.h
