### ISSUE TITLE
iknp testing protblem

### ISSUE THREAD

**Issue by JasonGaos** [osu-crypto/libOTe#102]
Hello Professor,

I am trying to test the iknp OT function but the message can not be send correctly.

The code and the running result are looking like this. Could you help to see what is the problem here?

Thanks.

![image](https://user-images.githubusercontent.com/31381946/210451184-4ac6b2cc-a32a-4441-8b1b-05808644c03e.png)
![image](https://user-images.githubusercontent.com/31381946/210451231-e07fb187-b762-45a9-8185-b9a68b8527c3.png)

**Comment by ladnir** [comment]
The library is coroutine based. `recv.receive(...)` and `sender.send(...)` by themselves do nothing. Instead, these functions return a `task<>` that can be awaited to actually run the protocol.  To fix your code you can do
```c++
macoro::sync_wait(macoro::when_all_ready(
    recv.receive(choices, recvMsg, prng0, sockets[0]),
    sender.send(sendMsg, prng1, sockets[1])
);
```

When this means in that you want to run both coroutines and then synchronously wait for both to finish.  For more about coroutines, you can see https://github.com/Visa-Research/coproto and https://www.youtube.com/watch?v=1Wy5sq3s2rg
