### ISSUE TITLE
throw runtime error when set mDebug=true in exampleVole.h

### ISSUE THREAD

**Issue by jianlinjiang** [osu-crypto/libOTe#109]
Hi, I met an error when I set `receiver.mDebug=true;` and `sender.mDebug = true;`  in `exampleVole.h`. I built `libote` in debug mode. Then I run the example program by `./frontend_libOTe -vole`, it throws runtime error in `libOTe/libOTe/Vole/Silent/SilentVoleReceiver.cpp:683`. When mdebug is set true, the program seems to check vole result, however it fails. Besides, if I don't set mDebug, the program finishes correctly. Is the phenomenon is expected?

**Comment by jianlinjiang** [comment]
No, I just want to verify the vole result. Okay, I will unset the flag. Thanks for your reply.

**Comment by ladnir** [comment]
As long as the unit test pass you should be good
