### ISSUE TITLE
cmake build error: python3 build.py --all --boost --sodium

### ISSUE THREAD

**Issue by longmarch2008** [osu-crypto/libOTe#110]
Consolidate compiler generated dependencies of target frontend_cryptoTools
[ 71%] Built target frontend_cryptoTools
[ 71%] Building CXX object libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/ConfigureCode.cpp.o
[ 71%] Building CXX object libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/Iknp/IknpOtExtSender.cpp.o
[ 72%] Building CXX object libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/Kos/KosOtExtReceiver.cpp.o
[ 73%] Building CXX object libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/Iknp/IknpOtExtReceiver.cpp.o
In file included from /root/MiniPSI/libOTe/libOTe/TwoChooseOne/ConfigureCode.cpp:1:
/root/MiniPSI/libOTe/libOTe/TwoChooseOne/ConfigureCode.h:2:10: fatal error: libOTe/Config.h: No such file or directory
    2 | #include "libOTe/Config.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [libOTe/CMakeFiles/libOTe.dir/build.make:384: libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/ConfigureCode.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
In file included from /root/MiniPSI/libOTe/libOTe/../libOTe/TwoChooseOne/TcoOtDefines.h:14,
                 from /root/MiniPSI/libOTe/libOTe/TwoChooseOne/Kos/KosOtExtReceiver.cpp:13:
/root/MiniPSI/libOTe/libOTe/../libOTe/TwoChooseOne/ConfigureCode.h:2:10: fatal error: libOTe/Config.h: No such file or directory
    2 | #include "libOTe/Config.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [libOTe/CMakeFiles/libOTe.dir/build.make:426: libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/Kos/KosOtExtReceiver.cpp.o] Error 1
In file included from /root/MiniPSI/libOTe/libOTe/../libOTe/TwoChooseOne/TcoOtDefines.h:14,
                 from /root/MiniPSI/libOTe/libOTe/TwoChooseOne/Iknp/IknpOtExtSender.cpp:7:
/root/MiniPSI/libOTe/libOTe/../libOTe/TwoChooseOne/ConfigureCode.h:2:10: fatal error: libOTe/Config.h: No such file or directory
    2 | #include "libOTe/Config.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [libOTe/CMakeFiles/libOTe.dir/build.make:412: libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/Iknp/IknpOtExtSender.cpp.o] Error 1
In file included from /root/MiniPSI/libOTe/libOTe/../libOTe/TwoChooseOne/TcoOtDefines.h:14,
                 from /root/MiniPSI/libOTe/libOTe/TwoChooseOne/Iknp/IknpOtExtReceiver.cpp:10:
/root/MiniPSI/libOTe/libOTe/../libOTe/TwoChooseOne/ConfigureCode.h:2:10: fatal error: libOTe/Config.h: No such file or directory
    2 | #include "libOTe/Config.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [libOTe/CMakeFiles/libOTe.dir/build.make:398: libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/Iknp/IknpOtExtReceiver.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:372: libOTe/CMakeFiles/libOTe.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

**Comment by ladnir** [comment]
fixed. thanks
