### ISSUE TITLE
A build problem

### ISSUE THREAD

**Issue by taxuexunshang** [osu-crypto/libOTe#112]
Hello, I'm trying to build v1.0.0 and I'm having the following problem with the following console output.
`/home/hongjian/ot-gc/libOTe/cryptoTools/cryptoTools/Crypto/RCurve.cpp: In member function 'void osuCrypto::REccNumber::init()':
/home/hongjian/ot-gc/libOTe/cryptoTools/cryptoTools/Crypto/RCurve.cpp:197:9: error: 'bn_init' was not declared in this scope; did you mean 'init'?
  197 |         bn_init(mVal, static_cast<int>(sizeDigits()));
      |         ^~~~~~~
      |         init
compilation terminated due to -Wfatal-errors.
make[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/build.make:258: cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/RCurve.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:239: cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/all] Error 2
make: *** [Makefile:136: all] Error 2`

This is the command I used to build
` cmake . -DENABLE_RELIC=ON -DENABLE_ALL_OT=ON`

Please help me to read this question in your free time, thanks!

**Comment by taxuexunshang** [comment]
I solved the problem above and now there is a new problem with a prompt like this
`/home/hongjian/old/libOTe/cryptoTools/cryptoTools/Crypto/RCurve.cpp: In member function 'bool osuCrypto::REccNumber::operator==(const osuCrypto::REccNumber&) const':
/home/hongjian/old/libOTe/cryptoTools/cryptoTools/Crypto/RCurve.cpp:240:38: error: 'CMP_EQ' was not declared in this scope
  240 |         return bn_cmp(*this, cmp) == CMP_EQ;
      |                                      ^~~~~~
compilation terminated due to -Wfatal-errors.
cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/build.make:257: recipe for target 'cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/RCurve.cpp.o' failed
make[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/RCurve.cpp.o] Error 1
CMakeFiles/Makefile2:220: recipe for target 'cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/all' failed
make[1]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by ladnir** [comment]
you need to make sure you're using the right version of relic. I dont recall which. Is this for ivory? Id suggest trying version 1.6 https://github.com/osu-crypto/libOTe/releases

**Comment by taxuexunshang** [comment]
Yes, I need to do some development using the Kyber OT with the parts in ivory. I based it on the old relic https://github.com/ladnir/relic/ provided in your v1.0.0 readme. Thanks for your suggestion, I'll try to build it on v1.6, thanks again for your help.
