### ISSUE TITLE
SilentOT runtime_error

### ISSUE THREAD

**Issue by addingIce** [osu-crypto/libOTe#113]
Hi, I tried to use SilentOT but got the following err:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  /libOTe/libOTe/Tools/SilentPprf.cpp:295
```
I used it by calling 'setBaseOts()' and 'send()/receive()'.

**Comment by ladnir** [comment]
you do not appear to be on master because the line number you gave in the error is not corresponding to the lastest code. 

https://github.com/osu-crypto/libOTe/blob/master/libOTe/Tools/SilentPprf.cpp#LL295C21-L295C46

What version of the library are you using?

**Comment by addingIce** [comment]
In fact I use https://github.com/ldr709/softspoken-implementation. (The commit of libOTe it used  is 3a40823f0507710193d5b90e6917878853a2f836).

**Comment by ladnir** [comment]
ok, how about you use the master branch?

**Comment by addingIce** [comment]
I tried to build the  master branch by `python build.py -DENABLE_IKNP=ON -DENABLE_KOS=ON -DENABLE_SOFTSPOKEN_OT=ON -DENABLE_SILENTOT=ON -DENABLE_SIMPLESTOT=ON --install=/root/libOTe-origin/libOTe/local`, but got the following err:
```
/root/libOTe-origin/libOTe/cryptoTools/cryptoTools/Crypto/SodiumCurve.cpp: In function ‘osuCrypto::Sodium::Monty25519 osuCrypto::Sodium::operator*(const osuCrypto::Sodium::Scalar25519&, const osuCrypto::Sodium::Monty25519&)’:
/root/libOTe-origin/libOTe/cryptoTools/cryptoTools/Crypto/SodiumCurve.cpp:147:9: error: ‘crypto_scalarmult_noclamp’ was not declared in this scope; did you mean ‘crypto_scalarmult_base’?
  147 |     if (crypto_scalarmult_noclamp(prod.data, a.data, b.data) < 0)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |         crypto_scalarmult_base
compilation terminated due to -Wfatal-errors.
make[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/build.make:286: cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/SodiumCurve.cpp.o] Error 1
```
...
```
CMake Error at out/build/linux/cryptoTools/cmake_install.cmake:93 (file):
  file INSTALL cannot find
  "/root/libOTe-origin/libOTe/cmake/../out//libdivide/libdivide.h": No such
  file or directory.
Call Stack (most recent call first):
  out/build/linux/cmake_install.cmake:47 (include)
```
I want to use KOS, softSpokenOT and silentOT, are the build options right?

**Comment by ladnir** [comment]
So this is an easy fix. It appears you have libsodium already on your system. LibOTe prefers a custom version with a few modifications. The solution is to either tell LibOTe to use the standard version of sodium or tell LibOTe to not use libraries that are installed on your system. Both of these options are detailed in the Readme. Let me know if you need more help.

**Comment by addingIce** [comment]
Thank you for you help, I can build it now. But I found that it used coproto::Socket for communication now, which was osuCrypto::Channel before. Could you tell me what's the reason for this change? If I still want to use  osuCrypto::Channel, could you give some advise?

**Comment by ladnir** [comment]
Sorry, forgot to respond. The new socket is coroutine based. This allows for more efficient asynchronous io. You can run many protocols all on a single connection with their "rounds" being compose concurrently.

Coproto has an AsioSocket which performs formal network io in a similar manner as Channel.

**Comment by addingIce** [comment]
Thanks a lot.
