### ISSUE TITLE
question about how to get the result by vole

### ISSUE THREAD

**Issue by jhjiang10** [osu-crypto/libOTe#114]
Hi and thanks for this great work!
I have a few questions。
![1686122283660(1)](https://github.com/osu-crypto/libOTe/assets/109639176/a06d9086-3d9d-47f4-8a47-72fc7f1e400c)
we can see  choice and msgs are  randomly generated in ExampleVole.h,but I have not seen that result.How to Verify correctness?What need i to see?Is msgs?

**Comment by ladnir** [comment]
take a look here https://github.com/osu-crypto/libOTe/blob/master/frontend/ExampleVole.h#L12

**Comment by jhjiang10** [comment]
> take a look here https://github.com/osu-crypto/libOTe/blob/master/frontend/ExampleVole.h#L12
Thanks！I've already seen it. But I still don't understand, after 20 ot, where can my results be seen? How to judge whether the ot result is correct or not?

**Comment by ladnir** [comment]
here is how you can check the output https://github.com/osu-crypto/libOTe/blob/master/libOTe_Tests/Vole_Tests.cpp#L62
