### ISSUE TITLE
Issue when building on MAC

### ISSUE THREAD

**Issue by haochenuw** [osu-crypto/libOTe#12]
libOTe/SimplestOT/fe25519_freeze.s:141:1: error: 32-bit absolute addressing is not supported in 64-bit mode

**Comment by ladnir** [comment]
Going to need more context than this... Are you on a 32 bit machine? Only 64 bit is supported...

**Comment by haochenuw** [comment]
My macbook should be 64-bit (it has core i9 CPU): 

https://en.wikichip.org/wiki/intel/core_i9/i9-7980xe

**Comment by ladnir** [comment]
yeah, I get the same error on my MAC machine. The assembly version of SimplestOT is only supported for GCC on Linux x64.
