### ISSUE TITLE
SoftSpoken Test question

### ISSUE THREAD

**Issue by lzjluzijie** [osu-crypto/libOTe#123]
I am confused by the small field test. From the description we should have `u` be a binary vector and delta similar to `v` and `w`, be in the test `delta` is a binary vector and `u` is shorter than `v` and `w`.

https://github.com/osu-crypto/libOTe/blob/ddf767f815d9319387c52276e9a9f29037c9bc58/libOTe/Vole/SoftSpokenOT/SmallFieldVole.h#L24-L29
https://github.com/osu-crypto/libOTe/blob/ddf767f815d9319387c52276e9a9f29037c9bc58/libOTe_Tests/SoftSpoken_Tests.cpp#L147

Also, I think `u[i]` should be `u[i / fieldBits]`, and `u` should be shorter than `w`?

https://github.com/osu-crypto/libOTe/blob/ddf767f815d9319387c52276e9a9f29037c9bc58/libOTe_Tests/SoftSpoken_Tests.cpp#L139

**Comment by ldr709** [comment]
I'll try rephrasing the comment, to hopefully help with your confusion. The reason why `v` and `w` are longer than `u` is that that `v` and `w` represents values over `GF(2^mFieldBits)`, while `u` represents values over `GF(2)`. That is, each entry of `u` is one bit long, but is `mFieldBits` long in `v` and `w`. These bits of `v` and `w` aren't stored contiguously though. Instead, they are stored with a stride of 128 bits, so the second bit of the first element of `v` is stored 128 bits after the first bit of the first element of `v`. Does that help?

You're correct the array index on line 139 is wrong. IIRC I mostly used this for debugging it while checking the i=0 iteration, so I didn't run into that bug.

**Comment by lzjluzijie** [comment]
That makes sense, thank you very much!
