### ISSUE TITLE
optimizations about silent ot

### ISSUE THREAD

**Issue by addingIce** [osu-crypto/libOTe#126]
Hi, a recent paper (https://eprint.iacr.org/2022/1431.pdf) proposes a suite of optimizations that can reduce the cost of GGM tree by half. What do you think of it and would you consider to implement it?

**Comment by ladnir** [comment]
its a great idea. It should be implemented but I have not gotten around to it. Would you want to? ;)

**Comment by ladnir** [comment]
done

**Comment by RanYoungL** [comment]
Hi, Peter, has this repo implemented the half-tree? I see you marked this issue as done

**Comment by ladnir** [comment]
I do not think it makes sense to use. Stationary syndrome decoding would be better anyways. Half tree requires additional setup so it's not a clear win when you have a small number of trees.
