### ISSUE TITLE
Issue when building on linux

### ISSUE THREAD

**Issue by haochenuw** [osu-crypto/libOTe#13]
.....(similar errors)
/usr/bin/ld: ../lib/libSimplestOT.a(gfe4x_square.s.o): relocation R_X86_64_32S against symbol `scale19' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../lib/libSimplestOT.a(fe25519_nsquare.s.o): relocation R_X86_64_32S against symbol `CONST_REDMASK51' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
frontend/CMakeFiles/frontend_libOTe.dir/build.make:128: recipe for target 'bin/frontend_libOTe' failed

**Comment by shreyasnbhat** [comment]
@ladnir Any insights on why this happens? I am also facing a similar error.

**Comment by ladnir** [comment]
Haven't had a chance to investigate. I'm the mean time I suggest enabling Relic instead.

**Comment by shreyasnbhat** [comment]
@ladnir I tried to build it with Relic using `cmake . -DENABLE_SIMPLESTOT=OFF -DENABLE_RELIC=ON -DENABLE_MIRACL=OFF`

The error I encountered now.
```/mnt/e/libOTe/cryptoTools/cryptoTools/Crypto/RCurve.cpp: In member function ‘const bn_st* osuCrypto::REccNumber::modulus() const’:
/mnt/e/libOTe/cryptoTools/cryptoTools/Crypto/RCurve.cpp:207:69: error: ‘ctx_t {aka struct _ctx_t}’ has no member named ‘ep_r’; did you mean ‘eb_r’?
     const bn_st * REccNumber::modulus() const { return &core_get()->ep_r; }
                                                                     ^~~~
                                                                     eb_r
compilation terminated due to -Wfatal-errors.
cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/build.make:374: recipe for target 'cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/RCurve.cpp.o' failed
make[2]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/Crypto/RCurve.cpp.o] Error 1
CMakeFiles/Makefile2:110: recipe for target 'cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/all' failed
make[1]: *** [cryptoTools/cryptoTools/CMakeFiles/cryptoTools.dir/all] Error 2
Makefile:129: recipe for target 'all' failed

```

Get the same error whether or not `SIMPLEST_OT` is `ON` or `OFF`.  Kindly investigate what causes such build errors. Thanks

**Comment by shreyasnbhat** [comment]
So it worked for me with Relic. Turns out it was a Relic issue.

**Comment by ladnir** [comment]
Yeah, you needed to turn ECC on or something.

**Comment by ladnir** [comment]
@haochenuw or @shreyasnbhat can you show me what 
> make VERBOSE=true

outputs?

**Comment by ladnir** [comment]
Closing due to being old...
