### ISSUE TITLE
SoftSpokenOT doesn't work when using non-power-of-two as the fieldBits parameter

### ISSUE THREAD

**Issue by sachaservan** [osu-crypto/libOTe#131]
When running SoftSpokenOT from the frontend with parameter "-f" set to anything other than a power of 2 causes the front-end to immediately exit. This issue can be narrowed down to:

```
if ((u64)delta_.size() != baseOtCount())
	throw RTE_LOC;
```
in SmallFieldVole.cpp, where delta_.size() = 128 while baseOTCount() = 129 (with "-f 3"). However, changing this if statement to check the rounded version computed with ```roundUpTo()``` causes downstream checks to fails. There is probably a very simple fix but I couldn't figure it out. In particular, I believe that setting the size of ```baseMsg``` correctly in  ExampleTwoChooseOne.cpp should help?  However, this needs to be done conditionally, based on whether SoftSpoken or another 1-out-of-2 OT protocol is being run.

**Comment by ladnir** [comment]
kk, ill look into it

**Comment by ladnir** [comment]
fixed in master, more issues with the example code.
