### ISSUE TITLE
frontend examples does not correctly flush sockets

### ISSUE THREAD

**Issue by xade93** [osu-crypto/libOTe#132]
In `frontend/ExampleTwoChooseOne.cpp`, line 327, the socket created earlier did not get flush properly before being destructed. When changing OT instance to a smaller number this bug reveals itself (as there is less time for it to flush automatically). For example when changing number of OT instance to $1<<2$, the problem aborts with error:
```
Socket was destroyed with pending operations. terminate() is being called. Await Socket::flush() before the destructor is called. This will ensure thatall pending operations complete. /usr/local/include/coproto/Socket/SocketScheduler.h:709
terminate called without an active exception
```

I have verified that adding `cp::sync_wait(chl.flush());` at the end of above function solves the issue. Not sure if this problem is present in other codes as I didnt read them.

**Comment by ladnir** [comment]
I think this was recently fixed. Looks like maybe multi thread still has this issue. Is that when you see it?
