### ISSUE TITLE
The network Problem

### ISSUE THREAD

**Issue by The-Miracl** [osu-crypto/libOTe#134]
Could you explain why this happens? And  do you have examples of using  network part? Thank you very much

 network receive error._autoName_0 ): Connection reset by peer
 at  /root/PSU_gai/libOTe/cryptoTools/cryptoTools/Network/Channel.cpp:819
terminate called after throwing an instance of 'std::runtime_error'

**Comment by ladnir** [comment]
What version of libOTe are you using?

**Comment by The-Miracl** [comment]
1.5

**Comment by ladnir** [comment]
Well the first error means the other party closed the connection. And then it seems the error isn't being handled and terminate is called.

Hard to say more than that without context.

**Comment by The-Miracl** [comment]
Thanks，i am going to try later.
