### ISSUE TITLE
libOTe does not build

### ISSUE THREAD

**Issue by 46wmt** [osu-crypto/libOTe#136]
<img width="546" alt="屏幕截图 2024-05-30 111934" src="https://github.com/osu-crypto/libOTe/assets/63411519/a8db85bf-bb7a-4ffa-bfff-97bb3be133e0">

**Comment by ladnir** [comment]
Can you share your full output from a clean build?

Might be a week or so before I can fix it.

**Comment by 46wmt** [comment]
Do you mean the cmakeoutput.log？
[CMakeOutput.log](https://github.com/osu-crypto/libOTe/files/15494097/CMakeOutput.log)

**Comment by ladnir** [comment]
No, what you screenshot but the whole thing.
