### ISSUE TITLE
Questions about codes in silent VOLE

### ISSUE THREAD

**Issue by lhq1** [osu-crypto/libOTe#137]
Some codes are used to accelerate matrix multiplication in dual LPN assumption, such as QC code, EA code, ExConv code et al. I have several questions:

1. For Tungsten code, I still don't know its definition and construction after searching for papers about PCG. Could you please provide some references? I also wonder about its features compared to ExConv code.

2. For the weight of noise vectors, I note there exists a lower bound: when length N is less than 512, it is 64; otherwise, it is 40. In [BCGI18], there doesn't exist such a lower bound. Could you please explain more? BCGI18: Compressing vector OLE.

By the way, I found a bug: In [syndromeDecodingConfigure](https://github.com/osu-crypto/libOTe/blob/90ad04d43663930c76d535e610f9ddc2cf3b2d05/libOTe/TwoChooseOne/ConfigureCode.h#L116), there should be `break` after line 133, otherwise, all configure of EA code will fail.

**Comment by ladnir** [comment]
1) There is no reference for Tungsten. It is experimental, use at your own risk, I make no promises that its secure. Maybe at some point I will be able to prove something but so far I have not been successful.

2) Here are some references https://eprint.iacr.org/2022/1014 https://eprint.iacr.org/2022/712

Thanks, ill take a look at the config

**Comment by ladnir** [comment]
fixed
