### ISSUE TITLE
Build Failure: Compilation Error in RegularPprf.h

### ISSUE THREAD

**Issue by sjsonucool** [osu-crypto/libOTe#139]
Hi there! I am using ubuntu 18.04.6 LTS. I encountered an issue while trying to build the library using the command `python build.py --all --boost --sodium`. The build process fails at 88% with the following error:

`[ 86%] Building CXX object libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/SoftSpokenOT/SoftSpokenMalOtExt.cpp.o
[ 86%] Building CXX object libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/SoftSpokenOT/SoftSpokenShOtExt.cpp.o
[ 86%] Building CXX object libOTe/CMakeFiles/libOTe.dir/Vole/SoftSpokenOT/SmallFieldVole.cpp.o
[ 87%] Linking CXX static library libtests_cryptoTools.a
[ 87%] Built target tests_cryptoTools
[ 87%] Building CXX object cryptoTools/frontend_cryptoTools/CMakeFiles/frontend_cryptoTools.dir/Tutorials/Network.cpp.o
[ 87%] Building CXX object cryptoTools/frontend_cryptoTools/CMakeFiles/frontend_cryptoTools.dir/main.cpp.o
[ 88%] Building CXX object cryptoTools/frontend_cryptoTools/CMakeFiles/frontend_cryptoTools.dir/signalHandle.cpp.o
In file included from /home/sonujha/libOTe/libOTe/../libOTe/TwoChooseOne/Silent/SilentOtExtReceiver.h:19,
                 from /home/sonujha/libOTe/libOTe/TwoChooseOne/Silent/SilentOtExtReceiver.cpp:1:
/home/sonujha/libOTe/libOTe/../libOTe/Tools/Pprf/RegularPprf.h: In member function ‘macoro::task<> osuCrypto::RegularPprfReceiver<F, G, CoeffCtx>::expand(osuCrypto::Socket&, osuCrypto::RegularPprfReceiver<F, G, CoeffCtx>::VecF&, osuCrypto::PprfOutputFormat, bool, osuCrypto::u64, CoeffCtx)’:
/home/sonujha/libOTe/libOTe/../libOTe/Tools/Pprf/RegularPprf.h:818:17: error: expected ‘catch’ at end of input
  818 |                 void clear()
      |                 ^~~~
compilation terminated due to -Wfatal-errors.
libOTe/CMakeFiles/libOTe.dir/build.make:439: recipe for target 'libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/Silent/SilentOtExtReceiver.cpp.o' failed
make[2]: *** [libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/Silent/SilentOtExtReceiver.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/sonujha/libOTe/libOTe/../libOTe/TwoChooseOne/Silent/SilentOtExtSender.h:18,
                 from /home/sonujha/libOTe/libOTe/TwoChooseOne/Silent/SilentOtExtSender.cpp:1:
/home/sonujha/libOTe/libOTe/../libOTe/Tools/Pprf/RegularPprf.h: In member function ‘macoro::task<> osuCrypto::RegularPprfReceiver<F, G, CoeffCtx>::expand(osuCrypto::Socket&, osuCrypto::RegularPprfReceiver<F, G, CoeffCtx>::VecF&, osuCrypto::PprfOutputFormat, bool, osuCrypto::u64, CoeffCtx)’:
/home/sonujha/libOTe/libOTe/../libOTe/Tools/Pprf/RegularPprf.h:818:17: error: expected ‘catch’ at end of input
  818 |                 void clear()
      |                 ^~~~
compilation terminated due to -Wfatal-errors.
libOTe/CMakeFiles/libOTe.dir/build.make:453: recipe for target 'libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/Silent/SilentOtExtSender.cpp.o' failed
make[2]: *** [libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/Silent/SilentOtExtSender.cpp.o] Error 1
In file included from /home/sonujha/libOTe/libOTe/../libOTe/Vole/SoftSpokenOT/SmallFieldVole.h:19,
                 from /home/sonujha/libOTe/libOTe/TwoChooseOne/SoftSpokenOT/SoftSpokenShOtExt.h:18,
                 from /home/sonujha/libOTe/libOTe/TwoChooseOne/SoftSpokenOT/SoftSpokenMalOtExt.h:12,
                 from /home/sonujha/libOTe/libOTe/TwoChooseOne/SoftSpokenOT/SoftSpokenMalOtExt.cpp:1:
/home/sonujha/libOTe/libOTe/../libOTe/Tools/Pprf/RegularPprf.h: In member function ‘macoro::task<> osuCrypto::RegularPprfReceiver<F, G, CoeffCtx>::expand(osuCrypto::Socket&, osuCrypto::RegularPprfReceiver<F, G, CoeffCtx>::VecF&, osuCrypto::PprfOutputFormat, bool, osuCrypto::u64, CoeffCtx)’:
/home/sonujha/libOTe/libOTe/../libOTe/Tools/Pprf/RegularPprf.h:818:17: error: expected ‘catch’ at end of input
  818 |                 void clear()
      |                 ^~~~
compilation terminated due to -Wfatal-errors.
libOTe/CMakeFiles/libOTe.dir/build.make:467: recipe for target 'libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/SoftSpokenOT/SoftSpokenMalOtExt.cpp.o' failed
make[2]: *** [libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/SoftSpokenOT/SoftSpokenMalOtExt.cpp.o] Error 1
In file included from /home/sonujha/libOTe/libOTe/../libOTe/Vole/SoftSpokenOT/SmallFieldVole.h:19,
                 from /home/sonujha/libOTe/libOTe/TwoChooseOne/SoftSpokenOT/SoftSpokenShOtExt.h:18,
                 from /home/sonujha/libOTe/libOTe/TwoChooseOne/SoftSpokenOT/SoftSpokenShOtExt.cpp:1:
/home/sonujha/libOTe/libOTe/../libOTe/Tools/Pprf/RegularPprf.h: In member function ‘macoro::task<> osuCrypto::RegularPprfReceiver<F, G, CoeffCtx>::expand(osuCrypto::Socket&, osuCrypto::RegularPprfReceiver<F, G, CoeffCtx>::VecF&, osuCrypto::PprfOutputFormat, bool, osuCrypto::u64, CoeffCtx)’:
/home/sonujha/libOTe/libOTe/../libOTe/Tools/Pprf/RegularPprf.h:818:17: error: expected ‘catch’ at end of input
  818 |                 void clear()
      |                 ^~~~
compilation terminated due to -Wfatal-errors.
In file included from /home/sonujha/libOTe/libOTe/Vole/SoftSpokenOT/SmallFieldVole.h:19,
                 from /home/sonujha/libOTe/libOTe/Vole/SoftSpokenOT/SmallFieldVole.cpp:5:
/home/sonujha/libOTe/libOTe/../libOTe/Tools/Pprf/RegularPprf.h: In member function ‘macoro::task<> osuCrypto::RegularPprfReceiver<F, G, CoeffCtx>::expand(osuCrypto::Socket&, osuCrypto::RegularPprfReceiver<F, G, CoeffCtx>::VecF&, osuCrypto::PprfOutputFormat, bool, osuCrypto::u64, CoeffCtx)’:
/home/sonujha/libOTe/libOTe/../libOTe/Tools/Pprf/RegularPprf.h:818:17: error: expected ‘catch’ at end of input
  818 |                 void clear()
      |                 ^~~~
compilation terminated due to -Wfatal-errors.
libOTe/CMakeFiles/libOTe.dir/build.make:495: recipe for target 'libOTe/CMakeFiles/libOTe.dir/Vole/SoftSpokenOT/SmallFieldVole.cpp.o' failed
make[2]: *** [libOTe/CMakeFiles/libOTe.dir/Vole/SoftSpokenOT/SmallFieldVole.cpp.o] Error 1
libOTe/CMakeFiles/libOTe.dir/build.make:481: recipe for target 'libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/SoftSpokenOT/SoftSpokenShOtExt.cpp.o' failed
make[2]: *** [libOTe/CMakeFiles/libOTe.dir/TwoChooseOne/SoftSpokenOT/SoftSpokenShOtExt.cpp.o] Error 1
[ 89%] Linking CXX executable frontend
[ 89%] Built target frontend
[ 89%] Linking CXX executable frontend_cryptoTools
[ 89%] Built target frontend_cryptoTools
CMakeFiles/Makefile2:678: recipe for target 'libOTe/CMakeFiles/libOTe.dir/all' failed
make[1]: *** [libOTe/CMakeFiles/libOTe.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
`

Please let me know if you need any more information or logs. I would appreciate any help in resolving this issue.

Thank you!

**Comment by ladnir** [comment]
fixed
