### ISSUE TITLE
Unit Tests Failing with Relic

### ISSUE THREAD

**Issue by shreyasnbhat** [osu-crypto/libOTe#14]
@ladnir  The `UnitTest 29 REccpPoint_Test` is failing for me. I'm using `relic-0.4`. 
From what I could make out this seems to be a relic related issue. It would be great if you could check this out. Thanks.

```
29 - REccpPoint_Test                         ga_br != ga_br2
(F793B5C394FBBF90DCC77200BD113B6EEF7A857077BC548852A80F64911446C5 , 9EF8C8A11C3FC805036E09FB5C68AEA2F14020B6999F9B3BDBFCA0DC7C2AF4C6 , 1                                                                )
(F793B5C394FBBF90DCC77200BD113B6EEF7A857077BC548852A80F64911446C5 , 9EF8C8A11C3FC805036E09FB5C68AEA2F14020B6999F9B3BDBFCA0DC7C2AF4C6 , 1                                                                )
(F793B5C394FBBF90DCC77200BD113B6EEF7A857077BC548852A80F64911446C5 , 9EF8C8A11C3FC805036E09FB5C68AEA2F14020B6999F9B3BDBFCA0DC7C2AF4C6 , 1                                                                )
Failed - ga_br != ga_br2   6ms

```

**Comment by ladnir** [comment]
Will do

**Comment by ladnir** [comment]
What relic commit are you on?

**Comment by ladnir** [comment]
Version 0.4 might be the issue. You should be on 0.5.

It's a weird error because Relic saying those strings/points are not equal but they are....

for Windows: https://github.com/ladnir/relic/blob/new_master/
for Linux/MAC: https://github.com/relic-toolkit/relic

**Comment by shreyasnbhat** [comment]
@ladnir Was able to make it work with Naor Pinkas BaseOT's. Updated Relic to the latest version. SimplestOT still has a problem though. Thanks for the help!

**Comment by ladnir** [comment]
yeah, i think you just need to pull libOTe to get simplestOT with Relic to work.
