### ISSUE TITLE
cmake build error: python3 build.py --all --boost --sodium

### ISSUE THREAD

**Issue by liubang123123** [osu-crypto/libOTe#141]
Scanning dependencies of target KyberOT
[  0%] Building CXX object macoro/macoro/CMakeFiles/macoro.dir/thread_pool.cpp.o
[  0%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/kem.c.o
[  0%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/poly.c.o
[  1%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/polyvec.c.o

g++.real: error: unrecognized command line option ‘-std=c++20’; did you mean ‘-std=c++2a’?

make[2]: *** [macoro/macoro/CMakeFiles/macoro.dir/build.make:76：macoro/macoro/CMakeFiles/macoro.dir/thread_pool.cpp.o] 
make[1]: *** [CMakeFiles/Makefile2:377：macoro/macoro/CMakeFiles/macoro.dir/all] 
[  1%] Building ASM object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/polyvec_pointwise_acc.s.o
[  2%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/fips202.c.o
[  2%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/reduce.c.o
[  3%] Building ASM object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/cbdeta4.s.o
[  3%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/cbdref.c.o
[  3%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/precomp.c.o
[  4%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/verify.c.o
[  4%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/indcpa.c.o
[  5%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/kex.c.o
[  5%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/consts.c.o
[  6%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/genmatrix.c.o
[  6%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/fips202x4.c.o
[  7%] Building ASM object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/ntt.s.o
[  7%] Building ASM object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/invntt.s.o
[  7%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/randombytes.c.o
[  8%] Building C object thirdparty/KyberOT/CMakeFiles/KyberOT.dir/KyberOT.c.o
[  8%] Linking C static library libKyberOT.a
[  8%] Built target KyberOT

**Comment by ladnir** [comment]
upgrade your compiler to one supporting cpp20.

**Comment by liubang123123** [comment]
I have updated to g++13, but there will still be related errors. 
bitpolymul already fetched. 
-- bitpolymulConfig.cmake : /home/liu/code/libOTe/out/install/linux/lib/cmake/bitpolymul 
-- Configuring done (54.1s) 
-- Generating done (0.1s) 
-- Build files have been written to: /home/liu/code/libOTe/out/build/linux 
[  0%] Building CXX object macoro/macoro/CMakeFiles/macoro.dir/thread_pool.cpp.o 
[  8%] Built target KyberOT 
In file included from /home/liu/code/libOTe/out/macoro/macoro/thread_pool.cpp:1: 
In file included from /home/liu/code/libOTe/out/macoro/macoro/thread_pool.h:8: 
In file included from /home/liu/code/libOTe/out/macoro/macoro/../macoro/coroutine_handle.h:8: 
/usr/bin/../ lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/coroutine:355:2: fatal error: "the <coroutine> header requires -fcoroutines" 
#error "the <coroutine> header requires -fcoroutines" 
1 error generated. 
make[2]: *** [macoro/macoro/CMakeFiles/macoro.dir/build.make:76：macoro/macoro/CMakeFiles/macoro.dir/thread_pool.cpp.o] error 1 
make[1]: *** [CMakeFiles/Makefile2:377：macoro/macoro/CMakeFiles/macoro.dir/all] error 2

**Comment by liubang123123** [comment]
> upgrade your compiler to one supporting cpp20.
I have updated to g++13, but there will still be related errors.

bitpolymul already fetched.
-- bitpolymulConfig.cmake : /home/liu/code/libOTe/out/install/linux/lib/cmake/bitpolymul
-- Configuring done (54.1s)
-- Generating done (0.1s)
-- Build files have been written to: /home/liu/code/libOTe/out/build/linux
[  0%] Building CXX object macoro/macoro/CMakeFiles/macoro.dir/thread_pool.cpp.o
[  8%] Built target KyberOT
In file included from /home/liu/code/libOTe/out/macoro/macoro/thread_pool.cpp:1:
In file included from /home/liu/code/libOTe/out/macoro/macoro/thread_pool.h:8:
In file included from /home/liu/code/libOTe/out/macoro/macoro/../macoro/coroutine_handle.h:8:
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/coroutine:355:2: fatal error: "the <coroutine> header requires -fcoroutines"
#error "the <coroutine> header requires -fcoroutines"
 ^
1 error generated.
make[2]: *** [macoro/macoro/CMakeFiles/macoro.dir/build.make:76：macoro/macoro/CMakeFiles/macoro.dir/thread_pool.cpp.o] error 1
make[1]: *** [CMakeFiles/Makefile2:377：macoro/macoro/CMakeFiles/macoro.dir/all] error 2
make: *** [Makefile:136：all] error 2

**Comment by ladnir** [comment]
seems g++13 is still a bit too old. You can work around this by removing the if statement surrounding `-fcourtine` at `out/macoro/macoro/CMakeLists.cmake`   line  https://github.com/ladnir/macoro/blob/master/macoro/CMakeLists.txt#L68, i.e.
```
    target_compile_options( macoro PUBLIC
        "-fcoroutines"
        )
```

**Comment by ladnir** [comment]
well actually I'm not sure. The CI is passing with GNU 11.4.0. But the workaround should work regardless.
