### ISSUE TITLE
A build error

### ISSUE THREAD

**Issue by ryeosa** [osu-crypto/libOTe#143]
bitpolymul already fetched.
-- bitpolymulConfig.cmake : /home/sasa/code/snni/libOTe/out/install/linux/lib/cmake/bitpolymul
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sasa/code/snni/libOTe/out/build/linux
Scanning dependencies of target KyberOT
[  0%] Building CXX object macoro/macoro/CMakeFiles/macoro.dir/thread_pool.cpp.o
Consolidate compiler generated dependencies of target KyberOT
[  8%] Built target KyberOT
In file included from /home/sasa/code/snni/libOTe/out/macoro/macoro/thread_pool.cpp:1:
/home/sasa/code/snni/libOTe/out/macoro/macoro/thread_pool.h: In constructor ‘macoro::thread_pool::work::work(macoro::thread_pool::work&&)’:
/home/sasa/code/snni/libOTe/out/macoro/macoro/thread_pool.h:230:39: error: ‘exchange’ is not a member of ‘std’
  230 |             work(work&& w) : mEx(std::exchange(w.mEx, nullptr)) {}
      |                                       ^~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [macoro/macoro/CMakeFiles/macoro.dir/build.make:76: macoro/macoro/CMakeFiles/macoro.dir/thread_pool.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:377: macoro/macoro/CMakeFiles/macoro.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I see https://github.com/osu-crypto/libOTe/issues/141 there is a similar problem, and my g++ is also 13

What should I do, which version of g++ is more suitable？

**Comment by ladnir** [comment]
as a quick fix add `#include <utility>` to the top of `/home/sasa/code/snni/libOTe/out/macoro/macoro/thread_pool.h`

Ill release a fix soon

**Comment by zhouxv** [comment]
> as a quick fix add `#include <utility>` to the top of `/home/sasa/code/snni/libOTe/out/macoro/macoro/thread_pool.h`
> 
> Ill release a fix soon

！！！ Until 12/06/2024，no fix

**Comment by ladnir** [comment]
Lost track of it due to it being closed. I'll take a look tonight.

**Comment by ladnir** [comment]
hopefully fixed.
