### ISSUE TITLE
coproto::Socket::close() must be awaited if called. Terminate is being called terminate called without an active exception

### ISSUE THREAD

**Issue by liubang123123** [osu-crypto/libOTe#145]
I have the following error while testing the program:
coproto::Socket::close() must be awaited if called.  Terminate is being called
terminate called without an active exception
How to solve it ?

**Comment by ladnir** [comment]
`co_await socket.close();`

Or

`sync_wait(socket.close());`

**Comment by liubang123123** [comment]
> `co_await socket.close();`
> 
> Or
> 
> `sync_wait(socket.close());`

Thank you,my question has been solved!
