### ISSUE TITLE
Do the silent and noisy vole codes implement silver or RRT23?

### ISSUE THREAD

**Issue by private-panda** [osu-crypto/libOTe#148]
In README, it says the silent VOLE codes implement RRT23 and BCGIKRS19; the noisy VOLE codes implement BCGIKRS19. But in the codes of silent ones and noisy ones, it still says "This code implements features described in [Silver: Silent VOLE and Oblivious Transfer from Hardness of Decoding Structured LDPC Codes]". In RRT23, it claims "silver codes should not be used". So I am confused about which paper the source codes implement in silent and noisy VOLE? Thanks!

**Comment by ladnir** [comment]
Yeah, that's text is there for other reasons. Silver is not available to use unless you set some special compile flags. You can choose from RRT, Expand accumulate, or quasi cyclic codes. RRT is the default.

**Comment by private-panda** [comment]
Got it. Thank you for your clarification.
