### ISSUE TITLE
ENABLE_NP_KYBER v.s. ENABLE_MR_KYBER

### ISSUE THREAD

**Issue by gconeice** [osu-crypto/libOTe#149]
Hi,

There are bunch of places in the repo where the macro ENABLE_NP_KYBER is used rather than ENABLE_MR_KYBER. Is this a typo or some special purpose?

Thank you very much!

**Comment by ladnir** [comment]
Hmm, must be a typo.

**Comment by gconeice** [comment]
I see, thanks for the response! One ENABLE_NP_KYBER is in `libOTe/Base/BaseOT.h`. Additionally, this file should include `MasnyRindalKyber.h`.
