### ISSUE TITLE
IKNPDotExtension for Semi Honest

### ISSUE THREAD

**Issue by shreyasnbhat** [osu-crypto/libOTe#15]
@ladnir If I need to use the `IKNPDotExtension` for the semi honest setting what do I do? The code for `IKNPDotExtension` seems to be doing additional stuff as it caters to the malicious setting.

So I need to use a C-OT for generating multiplication triplets, but couldn't find an appropriate extension to use in `libOTe`. Any pointers regarding this?

Thanks.

**Comment by ladnir** [comment]
Delta-OT (Dot or C-OT) ensures that all messages **{(m<sub>i,0</sub>, m<sub>i,1</sub>) |  i in 1,...,n }** have the invariant that  **delta=m<sub>i,0</sub> XOR m<sub>i,1</sub> = m<sub>i',0</sub> XOR m<sub>i',1</sub>**  for any **i,i'**.

This is exactly what the implementation does. Is there something specific you are concerned about?

**Comment by shreyasnbhat** [comment]
Yes. Delta OT is the one that I need.  I guess the `IKNPDotExtension` does a random OT and uses error correcting codes(BCH) which aren't needed for the semi honest case?
Additionally, say that I need to generate multiplication triplets, I need to use a general correlation function <strong>f<sub>i</sub>(x) = a<sub>0</sub> * 2<sup>i</sup> - x</strong> where a<sub>0</sub> is the share of the first party and being the <strong>bit number(0..bitlength-1)</strong>. So I'll need to choose between <strong>x</strong> and <strong>f(x)</strong> instead of <strong>x</strong> and <strong>x XOR delta</strong>.

So for this to work I guess I need a general correlation function and secondly the ability to choose my own messages. So this is what I was mainly looking for but couldn't quite find it. Would be great if you could help me out on this

**Comment by ladnir** [comment]
So that's not a BCH code. It's a random code.

Yeah, you might be right... That implementation was an adaptation from the malicious version where the malicious receiver might have some knowledge of the other message. But now that I think about it... that does not appear to be true in the semi-honest case.

Is there a citation of the semi-honest case actually not requiring the matrix multiplication? This would also reduce the communication overhead for this protocol...

Delta-OT is only for the  **x** and **x XOR delta** correlation. It does not give you an arbitrary correlation. Is there a paper you are trying to implement that uses Delta-OT for beaver triples?

**Comment by shreyasnbhat** [comment]
Yeah so I have been trying to implement beaver triplets as given in the [ABY](https://encrypto.de/papers/DSZ15.pdf) paper. They have used <strong>C-OT's</strong> with arbitrary correlations to do the same. I intend to use the same to go ahead with implementing the matrix triplets as given in the [SecureML Paper](https://eprint.iacr.org/2017/396.pdf).

I did check the [OTExtension](https://github.com/encryptogroup/OTExtension) written by the <strong>encrypto-group</strong> but found it to be a bit hard to use due to the lack of documentation. There is also a lot of inconsistency in terms of what they have done in the paper and what they have coded up.

> Is there a citation of the semi-honest case actually not requiring the matrix multiplication? This would also reduce the communication overhead for this protocol... 



I didn't quite understand the matrix multiplication part though. Could you elaborate?

**Comment by ladnir** [comment]
I will look into if I can optimize the semi-honest DOT protocol. You don't need to worry about it.

Ok, so the COT that secureML refers to is a custom correlation. There is no native OT protocol that directly gives you this. Here is how you would construct it. Use the normal IKNP protocol with the chosen message variant `sendChosen(...), receiveChosen(...)`. You can make the chosen messages the correlation you want.

If you want, you will have to implement the optimizations described in SecureML on your own...

**Comment by shreyasnbhat** [comment]
@ladnir Thanks for your inputs! I'll try this.

**Comment by shreyasnbhat** [comment]
@ladnir Another small doubt. The `IKNPOTExtension`  assumes a 128 bit OT operation right? And these 128 bits are being represented by  the SSE `_mm__m128i` data type. If I want the OT to support dynamic bit lengths is it possible to do it in `libOTe`?

**Comment by ladnir** [comment]
Use the random OTs to encrypt your messages. Send the encryptions.

If short messages, just XOR `M` with the key (this is the optimize Secure ML refers to). If long messages, use an encryption scheme, e.g. `M+PRNG(K)`.

**Comment by shreyasnbhat** [comment]
So say I want to do a 64 bit OT, then what should I exactly assuming I don't want to do the SecureML optimization. Just mask the upper 64 bits in `block` ?

**Comment by ladnir** [comment]
Yeah, one time pad encrypt the bits. Take the first N bits of the random OT as the N bit one-time-pad key.

**Comment by shreyasnbhat** [comment]
@ladnir I noticed a weird thing happening wrt Network code. Maybe you can help me understand what is wrong here.
```
void check2(Channel& channel,int role) {
    if(role == SENDER) {
        channel.asyncSend(toBlock(0,10));
        channel.asyncSend(toBlock(0,9));
        channel.asyncSend(toBlock(0,8));
        channel.asyncSend(toBlock(0,7));
    } else {
        std::vector<block> x(4);
        for(int i = 0; i < 4; i++) {
            channel.recv(x[i]);
            std::cout << x[i] << std::endl;
        }
    }
}
```

The received output is
```
00007fffe7f1e0e00000000000000007
00007fffe7f1e0e00000000000000007
00007fffe7f1e0e00000000000000007
00007fffe7f1e0e00000000000000007
```

whereas the expected output should have been 
```
00000000000000000000000000000a
000000000000000000000000000009
000000000000000000000000000008
000000000000000000000000000007
```

This is fixed if I use `send` instead of `asyncSend`. Say that I have a container that is something like `std::vector<std::array<std::vector<block>, 2>>` and this isn't supported by the network send. Any suggestions on how to do this?

**Comment by ladnir** [comment]
This is the intended behavior.

`asyncSend(...)` without a move means that the operation does not block and you the caller needs to manage the lifetime of the memory that you are providing. You did *not* do this.

`toBlock(...)` returns a *temporary* which `asyncSend(...)` takes a reference to and then immediately returns. Then the temporary memory is "free". Later, `asyncSend(...)` completes the send operation but at this point, it is sending the junk that is currently at the temporary memory location.

**Comment by ladnir** [comment]
This might be helpful. 

https://github.com/ladnir/cryptoTools/blob/master/frontend_cryptoTools/Tutorials/Network.cpp#L11

**Comment by ShiroNekoHouse** [comment]
> @ladnir Another small doubt. The `IKNPOTExtension` assumes a 128 bit OT operation right? And these 128 bits are being represented by the SSE `_mm__m128i` data type. If I want the OT to support dynamic bit lengths is it possible to do it in `libOTe`?

I have a problem that if I want to input a value longer than 128 bits to the `IKNPOTExtension`, how should I do? 

`If long messages, use an encryption scheme, e.g. M+PRNG(K).`

@ladnir I didn't quite understand the encryption here. How can it change a message longer than 128 bits to a definitely 128 bits? Would be great if you can help me. Thank you!

**Comment by ladnir** [comment]
You take the 128 bit seed k and expand it into an arbitrary length random string PRNG(k). You then xor this with your message m. Or you can run aes or whatever you want. The OT messages are just random keys.

**Comment by siamumar** [comment]
> Yeah, one time pad encrypt the bits. Take the first N bits of the random OT as the N bit one-time-pad key.

I was also looking for OT extension for messages with less than 128 bits. However, it looks to me that what you suggested would incur some redundant communication. Even if my messages are 64 bits, it would still take the same time as 128-bit messages. Is that correct?

**Comment by ladnir** [comment]
N is veriable. If your message is 64 bits, mask with the first 64 bits of the OT string

**Comment by siamumar** [comment]
Thanks a lot for the quick response! My concern is: if I am using the first N bits of the OT string, am I wasting the other (128-N) bits? Will the communication cost be dependent on N or be constant?

**Comment by ladnir** [comment]
IKNP internally requires 128 bits of communication per OT. This is true regardless of what you do with the OT string.

If you want to do chosen message OTs, where the chosen messages have N bits, then your total communication will at least be 128 + 2N bits.

- Say the sender has random 128 OT string `r0,r1`.
- The receiver has choice bit `b` and `rb`.
- The sender has chosen messages m0,m1.

Then the following should be performed.

- Sender sends  `s0 = m0 + truncate(N,r0),  s1 = m1 + truncate(N,r1)`
- Receiver outputs `mb = s0 + truncate(N, rb)`

Since s0,s1 are both N bits, the total communication is 128 + 2N.

**Comment by ladnir** [comment]
If you want less communication, then you can use SilentOT. For this, the amortized cost will just be 2N bits of communication. This is because SilentOT does not require 128 bits of communication per OT. Instead, if you are performing w random OTs, then it requires ~128 * log(w) bits of communication. Therefore when w is large, this is effectively 0.

**Comment by siamumar** [comment]
This helps a lot. Thank you!

**Comment by ladnir** [comment]
this is done.
