### ISSUE TITLE
Generating Binary Triples

### ISSUE THREAD

**Issue by elimbaum** [osu-crypto/libOTe#150]
We've recently introduced libOTe into our multi-party computation framework to enable 2PC. In particular, we're interested in using your implementation of Silent VOLE and Silent OT.

Generating multiplication triples from Silent VOLE is pretty straightforward with the interfaces you provide. We're doing the usual method of generating $2n$ VOLEs and using them to compute the middle terms of the secret-shared product. However, generating binary triples (for bitwise AND) is a little trickier.

When we generate $n$ Silent OTs, we can extract random OT correlations of the form

$$
\vec A = \vec B\ \oplus\ (\vec C \wedge D)
$$

where $\vec A,\vec B,\vec C$ are length-$n$ vectors of 128-bit blocks, and $D$ is a bit vector of length $n$ (assume $\wedge$ works elementwise in the natural way). We can't use this directly as a binary VOLE, because the datatypes don't match up.

Our current solution is to always generate $n=128k$ Silent OT, then take the block-wise transpose (using fast `transpose128` from libOTe). That is, we transpose each 128x128-bit block of the OT output. This way, we have a 128-bit value $D$ fixed for each group of 128 OTs:

$$
\begin{align}
A_0&=B_0\oplus (C_0 \wedge D_{(0)})\\
A_1&=B_1\oplus (C_1 \wedge D_{(0)}\\
&\dots\\
A_{127}&=B_{127}\oplus (C_{127} \wedge D_{(0)})\\
A_{128}&=B_{128}\oplus (C_{128} \wedge D_{(1)})\\
&\dots\\
A_{255}&=B_{255}\oplus (C_{255} \wedge D_{(1)})\\
A_{256}&=B_{256}\oplus (C_{256} \wedge D_{(2)})\\
&\dots
\end{align}
$$

Each of the values above are 128 bit strings, so we now have a valid bitwise correlation. And because of this, we can "chop up" each correlation, as needed, for the given bitwise AND we'd like to compute. (e.g. for `int32_t` correlations, chop each one above into 4 pieces).

This method works totally fine, but it feels inelegant. It's also not as efficient as it could be, because it requires a lot of data movement. I wanted to make sure I'm not missing something obvious, and wondering if you had a preferred solution for generating binary triples.

**Comment by ladnir** [comment]
Are you trying to compute uniformaly random binary OLE's and then convert that into uniformly random beaver triples?

binary OLE: `P0` holds `a, c0`; `P1` holds `b, c1`, such that `a,b,c0` are uniform and `a*b = c0 + c1` mod 2.
beaver triple: Parties holds a secret sharing of `a,b,c` such that `a*b=c` mod 2.

Given two OLEs you can convert them into a beaver triple. 

If this is what you want, then what you are doing is not secure. The correct way is to compute an OT and the convert it into an OLE.  

- The parties compute an OT: `P0` holds uniformly random `m0,m1 in GF(2^128)`; `P1` holds random `d in GF(2)` and `md`. 
- `P0` compute `a=d, c0 = LSB(md)`; `P1` computes `b=LSB(m0 + m1), c1 = LSB(m0)`.

**Comment by elimbaum** [comment]
Ah, thanks. I see my mistake -- I had mentally swapped which values needed to be uniformly random. I'll try implementing what you suggest.

Is this slightly wasteful? It seems like we're throwing away 127 bits of each message. Does libOTe provided support for (e.g.) 1-bit OT? At least in the `SilentOT` class, it looks like the datatype is hardcoded to `block`.

Though I suppose the complexity of chosen-message OT is independent of the message size, so maybe this is irrelevant?

**Comment by ladnir** [comment]
yes, is wasteful but thats the best you can do from a random OT. 

Im in the [process of implementing](https://github.com/osu-crypto/libOTe/tree/dpf) this https://eprint.iacr.org/2024/429. TDB when it will be released.

**Comment by ladnir** [comment]
Also, FYI, the OT->OLE protocol is implemented here https://github.com/Visa-Research/volepsi/tree/main/volePSI/GMW
