### ISSUE TITLE
what are the communication costs of silent VOLE and silient OT?

### ISSUE THREAD

**Issue by xxxxx-xxx** [osu-crypto/libOTe#152]
From the VOLE-PSI paper (https://eprint.iacr.org/2021/266), the communication cost  (in bits) of VOLE in libOTe is 2^17*k*n^0.05, where n is the number of evaluations. But from the blazing-psi paper (https://eprint.iacr.org/2022/320), the communication cost of subfield VOLE is 2^14.5*k, regardless of n. What are the communication costs of silent VOLE and the underlying silent OT by using [RRT23]?

**Comment by ladnir** [comment]
VOLE is something like 

`(log(n/t) + 1) * t * k + t * BASE_VOLE` bits where `t=60` or so and `t * BASE_VOLE` is the cost to do a smaller VOLE of size `t`. The default impl for this has `BASE_VOLE=k^2` but this could be optimized depending on what you are doing.

**Comment by ladnir** [comment]
if you want to be more accurate you can run the benchmark and check the communication overhead.
