### ISSUE TITLE
v2.1.0 libOTe fail to build

### ISSUE THREAD

**Issue by Azzzting** [osu-crypto/libOTe#155]
when I use v.2.1.0 libOTe and use the command : "python3 build.py --setup --all --boost --relic" , here shows:

gmake[2]: *** [macoro/CMakeFiles/macoro.dir/build.make:76：macoro/CMakeFiles/macoro.dir/thread_pool.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:134：macoro/CMakeFiles/macoro.dir/all] Error 2
gmake: *** [Makefile:136：all] Error 2
CMake Error at thirdparty/fetch.cmake:28 (message):
  Build failed (2).
Call Stack (most recent call first):
  thirdparty/getMacoro.cmake:44 (run)
  cmake/coprotoFindDeps.cmake:85 (include)
  CMakeLists.txt:21 (include)

CMake Error at cryptoTools/thirdparty/fetch.cmake:21 (message):
  Configure failed (1).
Call Stack (most recent call first):
  cryptoTools/thirdparty/getCoproto.cmake:50 (run)
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:222 (include)
  cryptoTools/CMakeLists.txt:163 (include)

and I try to change the getMacoro.cmake to ues "commit 8d27637cac2169f95e3a3456286384bb3d81e5ec",there also have errors:

gmake[2]: *** [macoro/CMakeFiles/macoro.dir/build.make:76：macoro/CMakeFiles/macoro.dir/thread_pool.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:134：macoro/CMakeFiles/macoro.dir/all] Error 2
gmake: *** [Makefile:136：all] Error 2

CMake Error at cryptoTools/thirdparty/fetch.cmake:21 (message):
  Configure failed (1).
Call Stack (most recent call first):
  cryptoTools/thirdparty/getCoproto.cmake:50 (run)
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:222 (include)
  cryptoTools/CMakeLists.txt:163 (include)
  
  
  What's this about?How can fix it ?

**Comment by ladnir** [comment]
Can you try the master branch?

**Comment by Azzzting** [comment]
For some reason I have to use libOTe v2.1.0，so I'd like to ask if there's a solution.Does this mean that none of the previous versions of libOTe will work?

**Comment by ladnir** [comment]
OK, I'll try building it. I suspect it's an issue with dependancies which should be an easy fix.

**Comment by Azzzting** [comment]
Thank you very much for your help.

**Comment by ladnir** [comment]
try the libOTe_v2.1 branch.

**Comment by ladnir** [comment]
make sure you update cryptoTools to be on the right commit. Remove the out/ folder before building.

**Comment by Azzzting** [comment]
Very useful. Thank you very much.
