### ISSUE TITLE
Meeting a "illegal instruction(core dumped)" error.

### ISSUE THREAD

**Issue by cnmzxu** [osu-crypto/libOTe#23]
When I build your libOTe library, I have successfully built the whole project with Relic. But i meet a "illegal instruction(core dumped)" error while running the bin/frontend_libOTe and bin/frontend_cryptotools. I meet this error both on my WSL ubuntu 18.04 on my laptop and a ubuntu dual os on the same laptop. Could you please offer me some help.

**Comment by cnmzxu** [comment]
The core dump info is here

> Program terminated with signal SIGILL, Illegal instruction.
> #0  osuCrypto::AES::setKey(long long __vector(2) const&) (this=0x6b89a0 <osuCrypto::mAesFixedKey>, userKey=...) at /home/minz/libs/libOTe/cryptoTools/cryptoTools/Crypto/AES.cpp:26
> 26	        mRoundKey[1] = keyGenHelper(mRoundKey[0], _mm_aeskeygenassist_si128(mRoundKey[0], 0x01));

**Comment by ladnir** [comment]
What type of CPU do you have?

**Comment by cnmzxu** [comment]
thank you! It helps me. I find it might be the problem of thinkpad. It seems that I cannot enable aes-ni on my laptop. So is it possible for me to fix this issue by modifying the code or sth else?

**Comment by ladnir** [comment]
Yeah, you can modify the code. Simply change the aes implementation to use a software version. If you want you can wrap this in a configurable `#ifdef ENABLE_AESNI` and create a pull request.
