### ISSUE TITLE
problem when build the libOTe on linux

### ISSUE THREAD

**Issue by freelyyu** [osu-crypto/libOTe#25]
when I run `make`，it occurs the following error.
![7ZMXRO$R5J5N%KP$4VM4MM2](https://user-images.githubusercontent.com/39991677/72674308-07ef4d80-3ab0-11ea-8290-bad2824d9302.png)

**Comment by ladnir** [comment]
So libOTe uses an older version of relic. It's linked in the readme. At some point I'll merge with relic master...

**Comment by freelyyu** [comment]
Thanks for your reply, when I run `./frontend_cryptoTools -tut` on ubuntu, it occurs a problem as shown in the first picture, what's more, I have installed boost under the directory `libOTe\cryptoTools\thirdparty\linux`, but when I run `cmake . `, it can find Boost,  when I print the value of `Boost_INCLUDE_DIR` and `Boost_LIBRARIES`,it's NULL as shown in the second picture, and I run `make` successfully.
![1](https://user-images.githubusercontent.com/39991677/73134014-2505bc80-406c-11ea-9d48-93d9bf96148c.png)

**Comment by freelyyu** [comment]
the second picture of the above problem
![3](https://user-images.githubusercontent.com/39991677/73134142-17513680-406e-11ea-98ca-47c4eab935b0.png)

**Comment by ladnir** [comment]
Those errors are part of the tutorial... That is the expected behavior.

There must be something wrong with your print statement. Plus the cmake file already prints them here https://github.com/ladnir/cryptoTools/blob/f84e0b6eed726cbff45c76bdd2566a9defc38a19/cryptoTools/CMakeLists.txt#L153

Are you saying that these print statements are what produce the lines in the screen shot?

**Comment by freelyyu** [comment]
In fact, I use the following statement to print them. 
```
message("**Boost_INCLUDE_DIR:" ${Boost_INCLUDE_DIR})
message("**Boost_LIBRARIES:" ${Boost_LIBRARY})
```
then I use the default statement to print them, they are still null.
```
message(STATUS "Boost_LIB: ${Boost_LIBRARIES}" )
message(STATUS "Boost_INC: ${Boost_INCLUDE_DIR}" )
```

**Comment by ladnir** [comment]
So the library builds but when you run cmake it prints those values as the empty/null string?

That's curious. I actually have no idea ha.

My guess is that there is something weird going on with it finding the installed version of boost.

**Comment by freelyyu** [comment]
Thanks for your help. I am also  confused,  maybe I need to re-uninstall and then install Boost. When I use the following statement to print the `Boost_include_directory`
`message(STATUS "Boost_INC: ${Boost_INCLUDE_DIRS}" )`
it shows the following. but I use the default ways to find boost(first search the hint location).
```
-- Boost  found.
-- Found Boost components:
   system;thread
-- Boost_LIB:
-- Boost_INC: /usr/local/include
```
