### ISSUE TITLE
Compiling KOS

### ISSUE THREAD

**Issue by NoaHadad** [osu-crypto/libOTe#32]
I tried to compile the library on ubuntu.

I ran the commands:
1) cmake . -DENABLE_MIRACL=ON -DENABLE_KOS=ON
2) make

And got this error: /home/noa/libOTe/libOTe_Tests/OT_Tests.cpp: In function ‘void tests_libOTe::DotExt_Kos_Test()’:
/home/noa/libOTe/libOTe_Tests/OT_Tests.cpp:551:3: error: **‘KosDotExtSender’ was not declared in this scope**
KosDotExtSender sender;

Can you help me to fix it?

Regards,
Noa

**Comment by ladnir** [comment]
should be fixed now.
