### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by zx199858** [osu-crypto/libOTe#36]
Hello, an error occurred when I ran cmake. -DENABLE_CIRCUITS=ON.
![Ubuntu 64 位-2020-10-15-17-14-11](https://user-images.githubusercontent.com/54979272/96103561-73186400-0f0a-11eb-895e-0489a58f3bff.png)

**Comment by zx199858** [comment]
![Uploading 2020-10-15-17-14-11.png…]()

**Comment by zx199858** [comment]
I tried to upgrade cmake and boost but still cannot install normally.

**Comment by ladnir** [comment]
Did you follow the instructions? Ie use the boost.get bash script?

**Comment by zx199858** [comment]
year，but the console shows that found suitable version “1.71.0”。

**Comment by zx199858** [comment]
And still failed to find boost

**Comment by ladnir** [comment]
try pulling and building. I slightly changed how boost is found.

**Comment by zx199858** [comment]
Thanks.It appears to run cmake successfully, but the console still displays a warning.
And an error occurred when I ran make.
![Uploading 2020-10-18 16-01-48 的屏幕截图.png…]()
![2020-10-18 16-02-24 的屏幕截图](https://user-images.githubusercontent.com/54979272/96361831-b3baec00-115b-11eb-8d6f-65241406e3c2.png)

**Comment by zx199858** [comment]
Now it looks like I can run the cmake command, but the console still displays a warning.

AND an error occurred when I ran make.

**Comment by zx199858** [comment]
![2020-10-18 16-01-48 的屏幕截图](https://user-images.githubusercontent.com/54979272/96362676-9557ef00-1161-11eb-913f-24300a255165.png)

**Comment by zx199858** [comment]
![2020-10-18 16-02-24 的屏幕截图](https://user-images.githubusercontent.com/54979272/96362689-a0128400-1161-11eb-889d-e9039043c9ed.png)

**Comment by zx199858** [comment]
Thanks ,now it looks like I can run the cmake command, but  an error occurred when I ran make.

**Comment by zx199858** [comment]
![2020-10-18 16-02-24 的屏幕截图](https://user-images.githubusercontent.com/54979272/96362831-b4a34c00-1162-11eb-950a-20ee5a46152d.png)

**Comment by ladnir** [comment]
Try deleting the cmake cache file and building again. Also, that warning means you need to enable a base ot. If on Linux, simplest OT asm is a good option.

**Comment by zx199858** [comment]
Again, the error was displayed when building target tests_cryptoTools.

**Comment by ladnir** [comment]
Any idea what the Chinese text says?

**Comment by zx199858** [comment]
![Screenshot from 2020-10-19 15-37-43](https://user-images.githubusercontent.com/54979272/96415760-9b150980-1221-11eb-94ea-68b6594ad7ff.png)

**Comment by zx199858** [comment]
![Screenshot from 2020-10-19 15-37-43](https://user-images.githubusercontent.com/54979272/96415878-ca2b7b00-1221-11eb-9350-fdce6a745e0d.png)

**Comment by zx199858** [comment]
![Screenshot from 2020-10-19 15-37-43](https://user-images.githubusercontent.com/54979272/96416034-065edb80-1222-11eb-926b-bf3a29c88bcc.png)

**Comment by ladnir** [comment]
Thats odd. I don't know what that error means. I just successfully built it on my machine. 

Im not sure.

**Comment by zx199858** [comment]
Thanks for your help. I tried to install it again and still failed. I'm not sure that cmake was executed correctly. It seems that it still can't find boost.
![2020-10-23 15-30-12 的屏幕截图](https://user-images.githubusercontent.com/54979272/96970240-f444ac00-1545-11eb-9524-458d2c033021.png)

I'll try to reinstall the system or build it on windows.
Thank you again.

**Comment by ladnir** [comment]
So make sure that boost is located at libOTe/cryptoTools/thirdParty/linux/boost

Or make sure that you only install boost 1.69.

The cmake script first looks for the thirdparty/boost directory. If it finds it, then I tell cmake no to look for the installed version of boost. Otherwise, it looks for the installed version.

**Comment by zx199858** [comment]
It seems that the problem lies in these two lines of code. Do you have any ideas?

![2020-10-25 09-28-17 的屏幕截图](https://user-images.githubusercontent.com/54979272/97097228-2a4e7100-16a9-11eb-8955-3273fe76e196.png)

cryptoTools/frontend_cryptoTools/CMakeFiles/frontend_cryptoTools.dir/build.make

**Comment by zx199858** [comment]
Thanks for your help.I successfully built it after reinstall the system.

**Comment by Jbai795** [comment]
> Thanks for your help.I successfully built it after reinstall the system.

Hi, I have the same problem as yours, could you please tell me what the 'reinstall system' means? Now, the problem happens in 'Built target tests_cryptoTools' phase as your second figure and the last figure.

**Comment by ladnir** [comment]
Do you have Boost installed on your system or at `libOTe/cryptoTools/thirdparty/linux/boost`?
