### ISSUE TITLE
The code for the naor-pinkas base OT does not fully comply with the NP01 suggestion

### ISSUE THREAD

**Issue by haibren** [osu-crypto/libOTe#40]
The algorithm in the NP01 paper says the random message encryption Mi is the output of H((PKi**r), R, i)  where i is the choice bit (or integer).
In the libOTe NaorPinkas class, the random messages are the output of H(i, point, R)  where i is the index counter of the OT (so not the same i). Indeed, it seems that adding this i counter is important when applying same R for multiple OTs. But the input of the choice bit i which appears in the paper is actually missing from the libOTe NaorPinkas code. In the code it is marked by variable u at the sender side, and by choice at the receiver side, but they both do not use it as an entry to the random oracle H.

NP01 justifies the need for this additional entry, at the end of the discussion part before section 3.1:
“Note that adding the index sigma [the choice bit] as a suffix […] in the call for H assures that the answers for PK0 and PK1 are independent, even if PK0 is chosen (maliciously) to be equal to PK1 by setting it to be square root of C[choice]”

This can be very easily avoided by adding an additional entry of the choice bit (or variable u, at the sender side) as an entry to the random oracle.

**Comment by ladnir** [comment]
Thanks for pointing this out. Just pushed a fix.
