### ISSUE TITLE
cuckoo stash overflow

### ISSUE THREAD

**Issue by heybrooo** [osu-crypto/libOTe#43]
@ladnir Hi, when I run the PSI task, the following prompt appears:
libOTe/cryptoTools/cryptoTools/Common/CuckooIndex.cpp:460
Exception info:cuckoo stash overflow

When I re-run, this prompt disappears. 
Why does this happen, is there any impact or is there any precautions?
Thanks~

**Comment by ladnir** [comment]
likely there are duplicates in the input set
