### ISSUE TITLE
/libOTe/out/build/linux" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by L-coder148** [osu-crypto/libOTe#45]
Hi，
Thank you for developing such a good library，I’m sorry to trouble you，I met the following problem：
![W$L4SSK}9H@MKEQN9Z748JS](https://user-images.githubusercontent.com/75669641/114384821-cde0fe80-9bc1-11eb-857c-e1bcc3c355b3.png)

**Comment by StarKirby1102** [comment]
Hello, I meet the same issue, how do you solve it? Thanks.
![image](https://user-images.githubusercontent.com/64449233/153982506-789bc87e-1798-4cb2-ac6c-49d463569b1c.png)

**Comment by ladnir** [comment]
You might need to update cmake?
