### ISSUE TITLE
no libraries placed in libOTe/lib and the binary frontend_libOTe  after running make

### ISSUE THREAD

**Issue by L-coder148** [osu-crypto/libOTe#46]
Hi，
I’m sorry to trouble you，I prefer installing the library using the old way rather than script, So I download the previous version as following.
![image](https://user-images.githubusercontent.com/75669641/114483825-aaf33080-9c3b-11eb-8203-5617ff1d928f.png)

But when I run `cmake . -DENABLE_KKRT=ON` and `make` successfully, There is no directory `bin` and` lib` .
![image](https://user-images.githubusercontent.com/75669641/114483818-a6c71300-9c3b-11eb-82bf-36b7b7e421f6.png)

**Comment by ladnir** [comment]
You should still be able to `install`. I am not supporting the previous way anymore. Feel free to just use the library from a commit that was working before.

**Comment by L-coder148** [comment]
thank you.
