### ISSUE TITLE
NcoOtExt generate base OT part without randomize

### ISSUE THREAD

**Issue by KyoohyungHan** [osu-crypto/libOTe#47]
https://github.com/osu-crypto/libOTe/blob/9dc5edb16085f70211e196046fd670812ad7aa46/libOTe/NChooseOne/NcoOtExt.cpp#L14

At the NcoOtExt, I think the receiver should randomize their base OT messages.
But, I can not find randomization of the block array of vector.
I wonder this is normal or not.

**Comment by KyoohyungHan** [comment]
I realize that "send" and "receive" is about random OT.

**Comment by ladnir** [comment]
Yeah, a bit confusing.
