### ISSUE TITLE
compile dynamic lib error

### ISSUE THREAD

**Issue by HaoXuan40404** [osu-crypto/libOTe#52]
Hello, I want to use libOTe in the java project, and then get an error message like:
like this:  ASM cannot set position for fpic flags in simplest,
![image](https://user-images.githubusercontent.com/34049754/125553894-8b2ccfa0-12a2-423c-bcbb-f65c1d57a390.png)

https://stackoverflow.com/questions/64853279/set-pic-flag-for-asm-compiling
is there possible to compile a dynamic library to libOTe and use ASM flags, thks a lot.

**Comment by ladnir** [comment]
No idea. Usually when you get that type of error it's a pain to fix. Try the suggestion that it gives you?

**Comment by HaoXuan40404** [comment]
> No idea. Usually when you get that type of error it's a pain to fix. Try the suggestion that it gives you?
Actually it's hard to set fpic flag for ASM command, like this https://stackoverflow.com/questions/64853279/set-pic-flag-for-asm-compiling，(◞‸◟ ) ， then I try use' gcc -shared *.o -o libOte.so -lz -lm' convert it to dynamic lib, also get another error

**Comment by HaoXuan40404** [comment]
When i use libmiracl.so and libcryptotool.so, and compile simplest OT, then get this
![image](https://user-images.githubusercontent.com/34049754/125592042-29f3e6ee-da67-480d-b440-f4e05d6dcabb.png)

**Comment by ladnir** [comment]
Miracl is no longer supported.

**Comment by HaoXuan40404** [comment]
Thks, I'll try the newest code

**Comment by HaoXuan40404** [comment]
commit  * 8879e47d46672ccadce5bcb42ce6ded79c2cb70d*(update version ) still face this problem 
![image](https://user-images.githubusercontent.com/34049754/125750726-30d3405f-0c2d-4a7c-aa5a-c9ba0405142e.png)

ubuntu 18.04
gcc 6.5 and gcc 7

but my mac could generate *.dylib success

**Comment by HaoXuan40404** [comment]
Those symbols cannot use independent code,
<img width="636" alt="wecom-temp-ab9cf697e59635f9bc528adbf8403699" src="https://user-images.githubusercontent.com/34049754/125783723-28dec37d-68db-4894-b526-133ce1fbf92d.png">

**Comment by adonis369** [comment]
If use kkrt protocal,can the SimplestOT  module be ignored?

**Comment by adonis369** [comment]
If use KKRT  protocol, can the SimplestOT module be ignored?
