### ISSUE TITLE
 libSimplestOT.a

### ISSUE THREAD

**Issue by adonis369** [osu-crypto/libOTe#53]
Does the kkrt function need libSimplestOT.a

**Comment by ladnir** [comment]
No, you just need to enable one of the base ots. You can for example, enable RELIC and MR.

**Comment by adonis369** [comment]
Does kkrt protocol not require module libSimplestOT？

**Comment by adonis369** [comment]
Reconfirm it

**Comment by ladnir** [comment]
It does not. Please don't spam issues with the same question.

You build just kkrt without simplest ot.

Delete the `out` folder if it exists.

```
python build.py -- -D ENABLE_RELIC=ON -D ENABLE_MR=ON -D ENABLE_KKRT=ON
```
This will build the library with relic (relic.a) and libOTe with the Masny Rindal base OT protocol and the kkrt protocol (libOTe.a). You do not need simplest ot. 

FYI, silent ot is now faster than kkrt, and sent a lot  less data.

**Comment by adonis369** [comment]
thank you very much
