### ISSUE TITLE
 libSimplestOT error

### ISSUE THREAD

**Issue by adonis369** [osu-crypto/libOTe#54]
use libSimplestOT.a  error
libSimplestOT.a(ge25519_p1p1_to_p3.s.o): relocation R_X86_64_32S against symbol `CONST_REDMASK51' can not be used when making a shared object; recompile with -fPIC

SimplestOT  CMakeLists.txt include  target_compile_options(SimplestOT PUBLIC -fpic)

**Comment by adonis369** [comment]
libpsi.a become libpsi.so,libpsi.so call  libSimplestOT.a

**Comment by ladnir** [comment]
Known issues, don't use asm simplest ot.
