### ISSUE TITLE
Is there an installation package WOLFSSL?

### ISSUE THREAD

**Issue by adonis369** [osu-crypto/libOTe#55]

**Comment by ladnir** [comment]
No, wolfssl is only partially supported. You will need to install it manually.

**Comment by adonis369** [comment]
有wolfssl 的tar安装包吗

**Comment by adonis369** [comment]
Do you have a tar package for wolfssl？

**Comment by adonis369** [comment]
I will need to install it manually

**Comment by ladnir** [comment]
No, I don't. Basically adding wolfssl was an experiment and isn't tested anymore.

If you want ssl, I would suggest using your own socket library which has ssl. You can write a socket adapter and give that to channel. Your socket will handle the ssl logic.
