### ISSUE TITLE
How to implement the KKRT16 OT Protocol?

### ISSUE THREAD

**Issue by JimmieLeung** [osu-crypto/libOTe#6]
I would like to implement the [KKRT16] 1-out-of-N oblivious transfer protocol by using libOTe. However, I don’t know how to invoke the API.

I would like to implement a program in Ubuntu 16.04 with two entities, Alice and Bob. Alice holds N different strings. Bob chooses one of them (maybe the i-th string). Then Alice and Bob invoke the [KKRT16] 1-out-of-N protocol. As a result, Bob knows the i-th string but nothing else. 

I would like to fix N to be a small number, less than 1000. Each message will be defined as a symmetric key (for example, a 128-bit key of AES encryption). How to implement this program? Are there any volunteers help me to build this program?

**Comment by ladnir** [comment]
see here for a working example 
https://github.com/osu-crypto/libOTe/blob/master/libOTe_Tests/NcoOT_Tests.cpp#L32

**Comment by avitalsh** [comment]
@ladnir could you please elaborate on how to work with chosen messages and not random? is the output of the KKRT OT always random?

**Comment by ladnir** [comment]
The output is always random. 

You can make it not random as follows. Say the receiver learns  r_{i,x_i}  for i = 1,...,m. The sender learns v_{i,j} for i= 1,...,m and j=0,...,N-1. 

If the sender wants to transmit the messages     m_{i,j} for i= 1,...,m and j=0,...,N-1. 

Then the sender sends e_{i,j} = m_{i,j} + r_{i,j}  to the receiver.

The receiver computes   m_{i,x_i} = r_{i,x_i} + e_{i,x_i}.

**Comment by ladnir** [comment]
libOTe now implements chosen message OTs. See `receiveChosen(...)` and `sendChosen(...)` in the main.cpp file.
