### ISSUE TITLE
PIR document

### ISSUE THREAD

**Issue by adonis369** [osu-crypto/libOTe#61]
Is there BgiPirTests.cpp code description document?

**Comment by ladnir** [comment]
you want a link to the BGI PIR paper?

**Comment by adonis369** [comment]
yes.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "osu-crypto/libOTe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 上午6:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [osu-crypto/libOTe] PIR document (Issue #61)





 
you want a link to the BGI PIR paper?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ladnir** [comment]
Function Secret Sharing: Improvements and Extensions. In:
 ACM CCS 16
