### ISSUE TITLE
i have a error when i build

### ISSUE THREAD

**Issue by TY-cc** [osu-crypto/libOTe#62]
i have a error when i build "python build.py --setup --boost --relic",as follow:

Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import cryptoTools.build
ModuleNotFoundError: No module named 'cryptoTools.build'

what should i do ?

**Comment by ladnir** [comment]
you need to checkout the submodule cryptoTools
```
git submodule update --init
```

**Comment by TY-cc** [comment]
The folder of cryptoTools is empty, ran your suggestion is still have same problem.

**Comment by ladnir** [comment]
You need to check out cryptoTools. You can also try to delete the whole repo and follow the Readme.

**Comment by TY-cc** [comment]
Thanks, just now i was building.  i single re-clone the cryptoTools, and build success follow the Readme.  But have two warning：

![image](https://user-images.githubusercontent.com/86347316/145171586-7a524f8d-342c-4d78-972b-cb2ba8140541.png)

is there a problem for the normally  use?
Sincere thanks again

**Comment by ladnir** [comment]
It's fine
