### ISSUE TITLE
Reason to remove SILVER?

### ISSUE THREAD

**Issue by alexanderzjs** [osu-crypto/libOTe#63]
@ladnir , may I know the reason to remove SILVER code? After going through the paper, I want to see the implementation, but it seems that it is removed according to https://github.com/osu-crypto/libOTe/commit/f931e50c90db5529b878fb6b2711269c7aa373a0.

Thanks

**Comment by ladnir** [comment]
Send me an email and I can explain.

**Comment by ladnir** [comment]
Silver is now back in the repo.

**Comment by alexanderzjs** [comment]
> Silver is now back in the repo.

Thanks, @ladnir
