### ISSUE TITLE
how to use the litobe

### ISSUE THREAD

**Issue by TY-cc** [osu-crypto/libOTe#64]

**Comment by TY-cc** [comment]
How  to use libote in my obj.  i used cmake , but defeated. i am a rookie. can you give me an exanple?  thanks

**Comment by ladnir** [comment]
1) build libOTe
```
git clone --recursive https://github.com/osu-crypto/libOTe.git
cd libOTe
python3 build.py --setup --boost --relic
python3 build.py -D ENABLE_RELIC=ON -D ENABLE_ALL_OT=ON
```
2) link libOTe into your project. In your `CMakeLists.txt`, you have to add something like
```
find_package(libOTe REQUIRED)
target_link_libraries(yourProject oc::libOTe)
```
3) tell cmake where to find libOTe & build
```
cd <your-project>
cmake . -D CMAKE_PREFIX_PATH=<path-to-libOTe>
make
```

**Comment by ladnir** [comment]
You can also install libOTe and then it will be the same except that the last step will be
```
cd <your-project>
cmake . -D CMAKE_PREFIX_PATH=<path-to-install-dir>
make
```

**Comment by TY-cc** [comment]
at the step 3, i get a CMAKE Error, as follow:
CMake Error in CMakeLists.txt:
  Imported target "oc::libOTe" includes non-existent path

    "/home/cc/CC/KKRT/libOTe-master/out/build/linux/libOTe/.."

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.


i am sure i had build t

**Comment by ladnir** [comment]
I take it that `/home/cc/CC/KKRT/libOTe-master/` is where you built libOTe.

Did you use the python script to build it?

It should have created the folder `/home/cc/CC/KKRT/libOTe-master/out/build/linux`. Is that the case?

**Comment by TY-cc** [comment]
i success. thanks!!  But i get new problem.
i want use "PRNG.h".  when i use "make", i get the error : /home/cc/CC/KKRT/src/main.cpp:1:10: fatal error: home/cc/CC/KKRT/libOTe/cryptoTools/cryptoTools/Crypto/PRNG.h: No such file or directory
    1 | #include "home/cc/CC/KKRT/libOTe/cryptoTools/cryptoTools/Crypto/PRNG.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sorry to trouble you !

**Comment by ladnir** [comment]
Not sure, my guess is you got your path wrong, maybe your missing the "-master" part. More generally, you should include `cryptoTools/Crypto/PRNG.h` and not your full path.

**Comment by TY-cc** [comment]
yes. my path is wrong.
i have revised path and success "make".  thanks .
another problem. Are there some different for the build and install?

**Comment by ladnir** [comment]
They should work the same.

**Comment by TY-cc** [comment]
OK, Thank you very much.
