### ISSUE TITLE
How to use the libOTe_Tests

### ISSUE THREAD

**Issue by StarKirby1102** [osu-crypto/libOTe#65]
Hello！I‘m a rookie. I want to test KKRT from libOTe_tests. Nevertheless I don't know how to use the libOTe_test's CmakeFiles. Could you please give an example for how to test the OTs? Thank you!!!
![image](https://user-images.githubusercontent.com/64449233/152179326-0f130cad-6972-44fe-a791-47ebf1c5f07e.png)
![image](https://user-images.githubusercontent.com/64449233/152179416-f113fe17-6c25-4ef5-82ac-3d7a7c2b08cd.png)

**Comment by ladnir** [comment]
the following should work
```
python3 ./build.py
./out/build/linux/frontend/frontend_libOTe -u kkrt
```

**Comment by StarKirby1102** [comment]
Thank you, this worked. Another qustion: My purpose is not to run the whole project. My own project cpp file has the interfaces of libOTe. I copied it to the same root directory and want to generate an executable file through _**g++ -o test test.cpp**_. Is this possible?

**Comment by ladnir** [comment]
Yes but I suggest cmake. Here's a project template https://github.com/ladnir/ProjectTemplate

If you want to directly compile with g++, you'll need to link the the libraries in out/install/linux/lib/ and libOTe, cryptoTools in out/build/linux/...

Then also do the includes out/install/linux and libOTe/, cryptoTools/cryptoTools

**Comment by StarKirby1102** [comment]
@ladnir Thanks! I'll try it.

**Comment by StarKirby1102** [comment]
Sorry, I meet the anther question when I cmake the test demo:
When I **_cd /home/user/libOTe/libOTe_Tests/cmakeTests_** to run the test:
![image](https://user-images.githubusercontent.com/64449233/152646965-6576dd38-d11e-4a3a-9a2f-38ba7af158cb.png)
I type **_cmake . -D CMAKE_PREFIX_PATH=/home/starkirby/libOTe/out/build/linux_** into the terminal, the error is:
![image](https://user-images.githubusercontent.com/64449233/152647047-bbced306-18fd-4c53-bc4d-f134e6921da1.png)

**Comment by StarKirby1102** [comment]
Hello teacher, the front span-lite issue had been solved. However, when I **_cmake ._** another question occur:
```C++
CMake Error at libOTe/out/build/linux/cryptoTools/cryptoToolsDepHelper.cmake:92 (message):
  could not find relic.  Add -DFETCH_RELIC=ON or -DFETCH_ALL=ON to auto
  download.
```
How to solve that, thanks! Sorry to disturb you again.

**Comment by ladnir** [comment]
You need to install relic and whatever else you are using (eg span). You can install them to that out/install/linux dir using the main libOTe build.py script. This calls cmake which will build and install them.

**Comment by ladnir** [comment]
Also take a look at the ProjectTemplate Readme. It talks about some of this

**Comment by StarKirby1102** [comment]
> You need to install relic and whatever else you are using (eg span). You can install them to that out/install/linux dir using the main libOTe build.py script. This calls cmake which will build and install them.
![image](https://user-images.githubusercontent.com/64449233/153522585-1645bcd5-4240-45dd-80bd-2fe27a078c13.png)

I check my out/install/linux, I have installed the relic before cmake:
This is my out/install/linux dir, I'm not sure if it has been installed.

**Comment by ladnir** [comment]
Is your code on github? I can take a look

**Comment by StarKirby1102** [comment]
> Is your code on github? I can take a look

Here is my code: I want to test the KKRT's N-choose-One OT, and I've copy the test demo to the main.cpp in the root dir. My purpose is to use its interface but I can't cmake it. Thank you for helping!
Here's my code: https://github.com/StarKirby1102/KKRT
![image](https://user-images.githubusercontent.com/64449233/153533357-b26d9551-e78a-445e-ae0b-3205c343ad17.png)

**Comment by ladnir** [comment]
change your headers to
```

#include "libOTe/TwoChooseOne/OTExtInterface.h"

#include "libOTe/Tools/Tools.h"
#include "libOTe/Tools/LinearCode.h"
#include <cryptoTools/cryptoTools/Network/Channel.h>
#include <cryptoTools/cryptoTools/Network/Session.h>
#include <cryptoTools/cryptoTools/Network/IOService.h>
#include <cryptoTools/cryptoTools/Common/Log.h>
#include <cryptoTools/cryptoTools/Common/TestCollection.h>

#include "libOTe/NChooseOne/Kkrt/KkrtNcoOtReceiver.h"
#include "libOTe/NChooseOne/Kkrt/KkrtNcoOtSender.h"
```

call cmake with `-DCMAKE_PREFIX_PATH=path/to/libOTe`. So assuming you are in your `KKRT` directory, call
```
cmake . -DCMAKE_PREFIX_PATH=./libOTe
```

**Comment by StarKirby1102** [comment]
> change your headers to
> 
> ```
> 
> #include "libOTe/TwoChooseOne/OTExtInterface.h"
> 
> #include "libOTe/Tools/Tools.h"
> #include "libOTe/Tools/LinearCode.h"
> #include <cryptoTools/cryptoTools/Network/Channel.h>
> #include <cryptoTools/cryptoTools/Network/Session.h>
> #include <cryptoTools/cryptoTools/Network/IOService.h>
> #include <cryptoTools/cryptoTools/Common/Log.h>
> #include <cryptoTools/cryptoTools/Common/TestCollection.h>
> 
> #include "libOTe/NChooseOne/Kkrt/KkrtNcoOtReceiver.h"
> #include "libOTe/NChooseOne/Kkrt/KkrtNcoOtSender.h"
> ```
> 
> call cmake with `-DCMAKE_PREFIX_PATH=path/to/libOTe`. So assuming you are in your `KKRT` directory, call
> 
> ```
> cmake . -DCMAKE_PREFIX_PATH=./libOTe
> ```

I try it follow your answer, but a new question has occured.
```c++
  Could not find a package configuration file provided by "span-lite" with
  any of the following names:

    span-liteConfig.cmake
    span-lite-config.cmake
```
However, I have install my project before runninig.
![image](https://user-images.githubusercontent.com/64449233/153537762-e714657d-d464-4908-91df-94001398d307.png)
Is there something missing?

**Comment by ladnir** [comment]
Here's what I did. I have two folders,

LibOTe
KKRT

I build libOTe as normal.

Then I  cloned your repo (without libOTe as a sub module)

Fixed your headers

Called `cmake . -DCMAKE_PREFIX_PATH=../libOTe`

In theory, libOTe can be anywhere.

**Comment by ladnir** [comment]
No, maybe you should get off VPN. 

Take a look at the cryptoTools/thirdparty/getXXXX.cmake files. You can manually download them and place them in the thirdparty folder and run the build.

You'll only need to do this for cryptoTools/thirdparty ( span, relic, boost). But libOTe has other dependancies depending on how it's configured.
