### ISSUE TITLE
How to print the intermediate result to debug?

### ISSUE THREAD

**Issue by StarKirby1102** [osu-crypto/libOTe#69]
I solved the installation of libOTe a few days ago, and I have successfully linked KKRT(1-out-of-N OT) into my project. 
Now I want to print some intermediate results to debug the program, in which **_block.h_** and **_Matrix.h_** classes I find that no override the << operators, so how to print this ? Directly **cout** will report an error.
The important intermediate results such as:
```C++
std::vector<block>recvMsgs(numOTs);
Matrix<block>sendMsgs(numOTs, numChosenMsgs);
```
How to print the data for these classes? Thanks!

**Comment by ladnir** [comment]
Iterate over them and print the block.
