### ISSUE TITLE
Trying to build libOTe on Ubuntu

### ISSUE THREAD

**Issue by sourabhmarathe** [osu-crypto/libOTe#7]
I got to the final step of the build process, but received this error. 

`../lib/libcryptoTools.a(sha1.cpp.o): In function `sha1_compress(unsigned int*, unsigned char const*)':
sha1.cpp:(.text._Z13sha1_compressPjPKh+0x1): undefined reference to `sha1_update_intel'
collect2: error: ld returned 1 exit status
frontend/CMakeFiles/frontend_libOTe.dir/build.make:180: recipe for target 'bin/frontend_libOTe' failed
make[2]: *** [bin/frontend_libOTe] Error 1
CMakeFiles/Makefile2:422: recipe for target 'frontend/CMakeFiles/frontend_libOTe.dir/all' failed
make[1]: *** [frontend/CMakeFiles/frontend_libOTe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

I am not sure if this is familiar to anyone here so I decided to post it. I am looking into it now.

**Comment by ladnir** [comment]
Sorry, this is my fault (I was over eager with my use of find and replace ;). If you pull cryptoTools you should get the fix. 

FYI, the assembly SHA1 implementation is something like 50% faster than the pure C++ Blake2 implementation (which is what you enable with `cryptoTools_NO_NASM`).

**Comment by sourabhmarathe** [comment]
I ran git submodule update --init --recursive, but I am still getting the same issue.

**Comment by ladnir** [comment]
If you haven't run cmake again you could try that, `cmake .`

I just built it on my Linux box.

**Comment by sourabhmarathe** [comment]
Yes. That has done it. Thank you very much.
