### ISSUE TITLE
Does this library support running on android and ios platforms? 

### ISSUE THREAD

**Issue by wcc19840827** [osu-crypto/libOTe#70]
Does this library support running on android and ios platforms? 
If supported, how should cross-compilation be configured in CMakeLists.txt?

**Comment by wcc19840827** [comment]
Boost not found when I use android.toolchain.cmake.

Use `find_package(Boost 1.77.0 COMPONENTS system thread regex ${ARGS})` to find boost lib.

 The error is `-- Could NOT find Boost (missing: Boost_DIR)`.

**Comment by ladnir** [comment]
did you build/install boost? You might need to play around with it a bit.
