### ISSUE TITLE
I have something confused with using this lib

### ISSUE THREAD

**Issue by InnovationFlash** [osu-crypto/libOTe#74]
I have installed this lib , but I have two problems in your lib:
1.Does this lib only implement the OT function instead of whole PSI?
2.Which test is kkrt's example?

Could you please solve my confusion？

Thank you.

**Comment by ladnir** [comment]
This library only implements OT like functionalities. Search the test and you should find the ones for kkrt.

If you want psi, take a like at libPSI

**Comment by InnovationFlash** [comment]
Thank you!
