### ISSUE TITLE
error building libOTe

### ISSUE THREAD

**Issue by hros** [osu-crypto/libOTe#77]
Following the build instructions, the command `python build.py --setup --boost --relic` fails with the error:
```
 /home/user/libOTe/cryptoTools/thirdparty/relic/src/md/blake2s-ref.c: In
  function ‘blake2s’:


  /home/user/libOTe/cryptoTools/thirdparty/relic/src/md/blake2s-ref.c:329:3:
  error: size of array element is not a multiple of its alignment

    329 |   blake2s_state S[1];
        |   ^~~~~~~~~~~~~
```

The computer is running Ubuntu 22.04 with g++ 12
attached is the cmake output log
[CMakeOutput.log](https://github.com/osu-crypto/libOTe/files/8755563/CMakeOutput.log)

**Comment by ladnir** [comment]
This is an issue with relic. Probably would need to bump its version to fix. A workaround would be to use libSodium instread. remove the `./out` folder and then build with `--sodium` instead of `--relic`

**Comment by hros** [comment]
first, thanks for the ultra-fast response
using sodium (with the command `python build.py --setup --boost --sodium`) seems to work. I did get the following warning:
```
CMake Warning at cmake/buildOptions.cmake:138 (message):
  NO Base OT enabled.
Call Stack (most recent call first):
  CMakeLists.txt:73 (include)
```
what about the next line: `python build.py -D ENABLE_RELIC=ON -D ENABLE_ALL_OT=ON`?
what should I change `-D ENABLE_RELIC=ON` to? `-D ENABLE_SODIUM=ON`?

**Comment by hros** [comment]
btw, following the relic compilation errors, I had a look at relic's readme which includes the following disclaimer:
```
RELIC is at most alpha-quality software. 
Implementations may not be correct or secure and may include patented algorithms. 
There are *many* configuration options which make the library horribly insecure. 
Backward API compatibility with early versions may not necessarily be maintained. 
Use at your own risk.
```
It is understandable they do not want any liability, but `≤ α quality`?

**Comment by ladnir** [comment]
I think they are just saying it can be used insecurely. You can also use libsodium which is production grade.
