### ISSUE TITLE
no type named ‘const_iterator’ in ‘class std::span<osuCrypto::block, 18446744073709551615>’

### ISSUE THREAD

**Issue by Yukinaaaaa** [osu-crypto/libOTe#78]
Something wrong with my libOTe.
no type named ‘const_iterator’ in ‘class std::span<osuCrypto::block, 18446744073709551615>’
![image](https://user-images.githubusercontent.com/74668748/170259002-e654dac9-c073-4983-bd4c-0f0a8d89496f.png)

What contributes to that problem and how can I fix it?

**Comment by ladnir** [comment]
yes, this is an issue with libOTe when you compile it with a new-ish compiler that has cpp-20. I'll push a fix soon. The fix would be to change `span<T>::const_iterator` to `span<T>::iterator` in `MatrixView.h`. Should be easy to do yourself if you want.

**Comment by ladnir** [comment]
fixed

**Comment by Yukinaaaaa** [comment]
thanks

**Comment by Yukinaaaaa** [comment]
Sorry for disturbing you again.
I have enabled allOT, but there are still some undefined references.
![6cb5963607c95037ee5c6143f86ff0eb](https://user-images.githubusercontent.com/74668748/172158995-3bb2fb67-43d2-46ff-a145-3a4b91de0cc6.png)
![ec94ad82dd915aa10f27d946a4b649b0](https://user-images.githubusercontent.com/74668748/172159019-e3d4119c-9134-4882-a2f9-35cf77eb0f39.png)

**Comment by ladnir** [comment]
Try to delete the out/ folder and rebuild. For some unknown reason it's lot linking the required libraries

**Comment by Yukinaaaaa** [comment]
I used this one.
python build.py --setup --boost --relic
python build.py -D ENABLE_RELIC=ON -D ENABLE_ALL_OT=ON --install=/home/yukina/PSU/environment

**Comment by ladnir** [comment]
OK, I'll look into it.

As a work around try to remove then install and then add it back if it builds
