### ISSUE TITLE
Question about Naor-Pinkas BaseOT

### ISSUE THREAD

**Issue by dnat112** [osu-crypto/libOTe#79]
I am trying to follow the implementation of the Naor-Pinkas base OT protocol. Is the libOTe implementation supposed to match the section titled "A single 1-out-of-2 oblivious transfer" in the NP01 paper? If so, could you point me to the place in the code where the sender sends "two encryptions, H(....) XOR M_0 and H(...) XOR M_1, to the chooser" ?

**Comment by ladnir** [comment]
The implementation does not encrypt messages. It just output random OT messages. The only input is the receiver's choice bit.

If you want chosen message OT you can call this function.  https://github.com/osu-crypto/libOTe/blob/master/libOTe/TwoChooseOne/OTExtInterface.h#L36

**Comment by dnat112** [comment]
Sorry, I am still a bit confused as I am new to this area. I am trying to use the IKNP OT extension with the NP base OT in a regular (not random or correlated) manner. I'm following the example in [ExampleTwoChooseOne.h](https://github.com/osu-crypto/libOTe/blob/master/frontend/ExampleTwoChooseOne.h). 

From what I can tell, in this example, when using the IKNP extension and NP as the base, the IKNP Sender (I-S) receives two elliptic curve group elements from the IKNP Receiver (I-R). I-S sends 128 PK0 values to I-R. When sendChosen/receiveChosen is called, I-R sends numOTs (e.g., 1 million) encryptions to I-S, and I-S sends 2*numOTs encryptions to I-R.

It seems that it is never necessary for I-R to send those 2k encryptions (the H(...) XOR M_i I mentioned above) to I-S. Why is this the case? (Apologies if this is obvious, but I have been unable to find a clear answer to this anywhere. The closest explanation I could find is on page 14 of [this paper](https://eprint.iacr.org/2013/552.pdf), but I don't know if this is related).

**Comment by ladnir** [comment]
Iknp says to set m0, m1 to be random. In this case you can optimize the base ot. Instead of sending random ot messages, you can instead have the base ot choose the random messages and return them. In this case we set m0 =H(...), m1=H(...). That is, we set m0, m1 to be the encryption keys that would have been used in the base ot protocol.

LibOTe uses "random" ot whenever possible. This is most of the time.

Make sense?

**Comment by dnat112** [comment]
>  In this case you can optimize the base ot.

Is there a paper or document that explains why this optimization is possible?

**Comment by ladnir** [comment]
https://eprint.iacr.org/2019/706 section 5

**Comment by ladnir** [comment]
Note that the full proof that's this is OK with the np protocol is not there. Instead that paper focuses on, if the base ot gives property X, the the ot extension results in security Y. What's left would be to actually prove np gives property X. In particular, libOTe defaults to the strongest base ot security notion of uniformly random base ots. And the choice bits are also rerandomized. 

I'm the semi honest setting everything is pretty easy to prove. It's a bit trickier for malicious which is what that paper focuses on.
