### ISSUE TITLE
More information on how to use this?

### ISSUE THREAD

**Issue by sourabhmarathe** [osu-crypto/libOTe#8]
Hello, 
I am trying to use kkrt as an OPRF in a wider protocol. I wanted to have two parties, one with an input, and the other running the PRF. I was wondering if could give any assistance with understanding how to interface with this library in a broader context. From what I can see, frontend.exe is only for benchmarking the code, but I could be mistaken.

**Comment by ladnir** [comment]
Yes, documentation [here](https://github.com/osu-crypto/libOTe/blob/master/libOTe/NChooseOne/NcoOtExt.h) and examples [here](https://github.com/osu-crypto/libOTe/blob/master/libOTe_Tests/NcoOT_Tests.cpp).

**Comment by sourabhmarathe** [comment]
Thank you.
