### ISSUE TITLE
Correlated OT example?

### ISSUE THREAD

**Issue by dnat112** [osu-crypto/libOTe#80]
I see a few examples/tests using the receiveChosen/sendChosen functions, but I haven't been able to find any examples using the receiveCorrelated/sendCorrelated functions for the OTExtReceiver/OTExtSender. Could you please add a test or example using these functions? 

Specifically, could you provide some examples of what would typically be input as the CorrelationFunction parameter in sendCorrelated?

Thank you

**Comment by ladnir** [comment]
Well you can see how it's implemented. 

For each ot the sender gets a random message m0. The receiver learns m0 if they have zero choice bit. Otherwise they learn corFn(m0, i). Here i is the ot index.

**Comment by dnat112** [comment]
I am specifically wondering about the corFn function. Could you give some examples of what cofFn would be, or what it would typically be?

**Comment by ladnir** [comment]
`auto corFn = [x=42](block m0, u64 i){return m0 +block(0,x);}; `

This would make all the ot messages (m0, m1) differ by having m1 be m0 plus 42.

Some applications want to have ots like this. If you're not family with it, likely you don't need it.
