### ISSUE TITLE
 error: ‘KkrtNcoOtSender’ was not declared in this scope

### ISSUE THREAD

**Issue by shazi4399** [osu-crypto/libOTe#88]
Hi, teacher.
I found #ifdef ENABLE_KKRT in the installed header file, but I did not define the variable ENABLE_KKRT in test_libote.

So my program show "KkrtNcoOtSender' was not declared in this scope" when compiling

Sincerely ask how to solve it? Or is there something wrong with my libOte installed?

Here's my code: [https://github.com/shazi4399/learnMakefile/tree/main/test_libote](https://github.com/shazi4399/learnMakefile/tree/main/test_libote)

**error message**
![image](https://user-images.githubusercontent.com/25169930/192919759-4d14e6a2-c5dc-47e1-936c-08098e96feac.png)

**Comment by ladnir** [comment]
Read the Readme

Python3 build.py -DENAABLE_KKRT
