### ISSUE TITLE
Building on MAC

### ISSUE THREAD

**Issue by sourabhmarathe** [osu-crypto/libOTe#9]
Similar issue from earlier today, after running make: 
`[ 94%] Linking CXX executable ../bin/frontend_libOTe
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "_sha1_update_intel", referenced from:
      sha1_compress(unsigned int*, unsigned char const*) in libcryptoTools.a(sha1.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/frontend_libOTe] Error 1
make[1]: *** [frontend/CMakeFiles/frontend_libOTe.dir/all] Error 2
make: *** [all] Error 2`
This was on a MAC, and the submodule was updated along with running `cmake .`.

**Comment by ladnir** [comment]
ok, did you call  `export cryptoTools_NO_NASM` as the readme instructs?

**Comment by sourabhmarathe** [comment]
Yes, I have set it to true.

**Comment by ladnir** [comment]
hmm, ok. The relevant place to look is [here](https://github.com/ladnir/cryptoTools/blob/5678aa6515eb4e49da98d5cb319c31ebeccb93e6/cryptoTools/CMakeLists.txt#L14). This defines `NO_INTEL_ASM_SHA1=1` which in turn should make the preprocessor disable the code that calls `_sha1_update_intel`. 

Can you double check that this is happening? Maybe a CMake `message("defining NO_INTEL_ASM_SHA1")` next to that line and then call `cmake .`.

**Comment by sourabhmarathe** [comment]
Yes, I am seeing this after running `cmake .`
`-- ENV{cryptoTools_NO_NASM} = true
defining NO_INTEL_ASM_SHA1`

**Comment by ladnir** [comment]
ok, and then in the sha1.cpp file its still calling that function? maybe just add some illegal code before that second line i linked to. To make sure/see if its not being called..

**Comment by sourabhmarathe** [comment]
Yes, when I add illegal code cmake . does not work.

**Comment by ladnir** [comment]
"does not work." as in it thoses an error on the code you added or the original error?

Assuming its the formaer, somehow we are defining `NO_INTEL_ASM_SHA1` and still getting through [this preprocessor line](https://github.com/ladnir/cryptoTools/blob/5678aa6515eb4e49da98d5cb319c31ebeccb93e6/cryptoTools/Crypto/sha1.cpp#L38). That seems very strange.   As a hack you can just uncomment [this line](https://github.com/ladnir/cryptoTools/blob/5678aa6515eb4e49da98d5cb319c31ebeccb93e6/cryptoTools/Crypto/sha1.cpp#L33).

**Comment by sourabhmarathe** [comment]
The code that was added caused the error. It looks like uncommenting that line of code does the trick on the MAC.
