### ISSUE TITLE
when i build libOTe in volepsi,i find a bug?

### ISSUE THREAD

**Issue by nihaoqingtuan** [osu-crypto/libOTe#93]
when i build libOTe in volepsi,first it tell me that libsodium auto-build failed, so i just installed it manually.then it goes wrong. it says crypto_scalarmult_noclamp is not in namespace.then i find that the stable libsodium delete this function. but you can see it in github
https://github.com/osu-crypto/libsodium/blob/master/src/libsodium/crypto_scalarmult/crypto_scalarmult.c

int
crypto_scalarmult_noclamp(unsigned char *q, const unsigned char *n,
                          const unsigned char *p)
{
    return crypto_scalarmult_curve25519_noclamp(q, n, p);
}

The reason volepsi doesn't compile is because of what I said above？

**Comment by ladnir** [comment]
My best guess is that you must have installed libsodium on your own... The default build of libOTe requires a modified version of libsodium. Yet the build system found libsodium on your system so used that version. Hence the mismatch.

You have two options, in the libOTe directory, you can either

- `python3 build.py -D SODIUM_MONTGOMERY=OFF`
- `python3 build.py -D FETCH_SODIUM=true`

The first will diable the features that make use of the modified version of libsodium while the second will download and build the modified version of libsodium.

To then build volepsi, you will need to build libOTe as described and then delete the `volepsi/out` and rebuild volepsi, i.e. `python3 build.py`

**Comment by nihaoqingtuan** [comment]
Do you know how to delete the compiled volepsi cleanly? Because I deleted and downloaded volepsi yesterday and found that there are a lot of things left, and the compilation process is also different from the original. I can't do what you just said.

**Comment by nihaoqingtuan** [comment]
when i build volepsi,error happens:
CMake Error at cmake/findDependancies.cmake:58 (find_package):
  By not providing "FindlibOTe.cmake" in CMAKE_MODULE_PATH this project has                                                  
  asked CMake to find a package configuration file provided by "libOTe", but                                                 
  CMake did not find one.                                                                                                    
                                                                                                                             
  Could not find a package configuration file provided by "libOTe" with any                                                  
  of the following names:                                                                                                    
                                                                                                                             
    libOTeConfig.cmake                                                                                                       
    libote-config.cmake                                                                                                      
                                                                                                                             
  Add the installation prefix of "libOTe" to CMAKE_PREFIX_PATH or set                                                        
  "libOTe_DIR" to a directory containing one of the above files.  If "libOTe"                                                
  provides a separate development package or SDK, be sure it has been                                                        
  installed.                                                                                                                 
Call Stack (most recent call first):                                                                                         
  cmake/findDependancies.cmake:72 (FIND_LIBOTE)                                                                              
  CMakeLists.txt:13 (include)    


so i try to build thirdparty/libOTe ,error happens:
CMake Error at cryptoTools/thirdparty/fetch.cmake:35 (message):
  Autogen failed (1).                                                                                                        
                                                                                                                             
  LOG:                                                                                                                       
                                                                                                                             
  vvvvvvvvvvvvv RUN Cloning https://github.com/osu-crypto/libsodium.git                                                      
  vvvvvvvvvvvv                                                                                                               
                                                                                                                             
  /usr/bin/git;clone;https://github.com/osu-crypto/libsodium.git                                                             
                                                                                                                             
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                        
                                                                                                                             
  vvvvvvvvvvvvv RUN Checkout 4e825a68baebdf058543f29762c73c17b1816ec0                                                        
  vvvvvvvvvvvv                                                                                                               
                                                                                                                             
  /usr/bin/git;checkout;4e825a68baebdf058543f29762c73c17b1816ec0                                                             
                                                                                                                             
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                        
                                                                                                                             
  vvvvvvvvvvvvv RUN Autogen vvvvvvvvvvvv                                                                                     
                                                                                                                             
  ./autogen.sh;-s                                                                                                            
                                                                                                                             
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                        
                                                                                                                             
  vvvvvvvvvvvvv RUN Checkout 4e825a68baebdf058543f29762c73c17b1816ec0                                                        
  vvvvvvvvvvvv                                                                                                               
                                                                                                                             
  /usr/bin/git;checkout;4e825a68baebdf058543f29762c73c17b1816ec0                                                             
                                                                                                                             
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                        
                                                                                                                             
  vvvvvvvvvvvvv RUN Autogen vvvvvvvvvvvv                                                                                     
                                                                                                                             
  ./autogen.sh;-s                                                                                                            
                                                                                                                             
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                        
                                                                                                                             
Call Stack (most recent call first):                                                                                         
  cryptoTools/thirdparty/getSodium.cmake:59 (run)                                                                            
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:137 (include)                                                                 
  cryptoTools/CMakeLists.txt:131 (include)                


so i try to download libsodium myself.Then there will be the question asked at the beginning

**Comment by ladnir** [comment]
You likely deleted the `thirdparty ` folder itself. That's incorrect. You were supposed to delete the folders that are inside it...

I suggest just deleting everything and clone again. 

Or do a git checkout of the missing files...

**Comment by nihaoqingtuan** [comment]
I redownloaded volepsi. so i don't delete anything. I am now /volepsi/thirdparty/libOTe/cryptoTools/thirdparty/libsodium
Cannot install with command ./autogen.sh

[nihaoqingtuan@LIN-4C855C1D01E libsodium]$ ./autogen.sh
If you are looking to install a stable version of libsodium,
please do not run arbitrary, undocumented commands.

Installation instructions are available at https://libsodium.org

**Comment by ladnir** [comment]
The following should work

git clone volepsi
cd volepsi/thirdparty
git clone libOTe
cd libOTe
python3 build.py -D FETCH_SODIUM=true --setup
cd ../..
python3 build.py

**Comment by nihaoqingtuan** [comment]
when i do "python3 build.py -D FETCH_SODIUM=true --setup" .error happen:

============= Building Sodium =============
Cloning https://github.com/osu-crypto/libsodium.git
'/usr/bin/git' 'clone' 'https://github.com/osu-crypto/libsodium.git'
Checkout 4e825a68baebdf058543f29762c73c17b1816ec0 
'/usr/bin/git' 'checkout' '4e825a68baebdf058543f29762c73c17b1816ec0'
Autogen
'./autogen.sh' '-s'
CMake Error at cryptoTools/thirdparty/fetch.cmake:35 (message):
  Autogen failed (1).                                                                                                        
                                                                                                                             
  LOG:                                                                                                                       
                                                                                                                             
  libtool is required, but wasn't found on this system                                                                       
                                                                                                                             
Call Stack (most recent call first):                                                                                         
  cryptoTools/thirdparty/getSodium.cmake:65 (run)                                                                            
  cryptoTools/cmake/cryptoToolsDepHelper.cmake:137 (include)                                                                 
  cryptoTools/CMakeLists.txt:132 (include)                                                                                   
                                                                                                                             
                                                                                                                             
-- Configuring incomplete, errors occurred!

**Comment by nihaoqingtuan** [comment]
i think i should download libtool

**Comment by nihaoqingtuan** [comment]
it works. thank you
