### ISSUE TITLE
A question about the messgae length of kkrt

### ISSUE THREAD

**Issue by qwerfdg** [osu-crypto/libOTe#94]
Hi!
I think kkrt is a protocol that can be considered as pir. So, I use it to query one of the n messages database. One problem is that the message in the database is usually larger than 128bit. I found a note in the code [here](https://github.com/osu-crypto/libOTe/blob/7c3746d39fc39d4f0b18d73151135b6477c6fb43/libOTe/NChooseOne/Kkrt/KkrtNcoOtReceiver.cpp#L318). How can I query message larger than 128bit? Maybe I should modify the storage structure of data "block" ?

**Comment by ladnir** [comment]
One can describe ot as something similar to pir but for the most part that's not what libOTe implements. LibOTe primarily generates random ots. For kkrt, that means the sender can generate N random 128 bit strings per ot. The receiver gets to learn exactly 1 of these N random strings. Currently N=2^76.

To then transmit chosen messages, you can encrypt the messages under these random ot strings, using the strings as encryption keys. An example of this is implemented for 1 out of 2 ot. But you'll have to implement it for kkrt.

**Comment by qwerfdg** [comment]
To reduce the number of communication rounds and the amount of communication data, perhaps I can directly use kkrt to select one of the N chosen messages. I just need to replace [prng](https://github.com/osu-crypto/libOTe/blob/7c3746d39fc39d4f0b18d73151135b6477c6fb43/frontend/ExampleNChooseOne.h#L192l) with chosen messages. But the chosen messages should not greater than 128bit in libOTe. In order to query more than 128bit message, maybe I need modify the storage structure of data "block" in kkrt. Do you think the security of this method is equivalent to what you said above? What's more, is it worth studying and easy to realize?

**Comment by ladnir** [comment]
You can easily extend the code to do chosen message with strings of length greater than 128. Morally it will work the same way as sendChosen.

You encrypt your chosen message under the random 1 out of N ot strings.

What's currently implemented is this with one time pad encryption. As such, you can only do this with 128 bit messages. However, you can also do this with other encryption algorithms that allow you to encrypt longer strings.

Do not modify block. That will not work.

Feel free to look into it. It's nothing ground breaking but a decent exercise to implement and learn from...

**Comment by qwerfdg** [comment]
Okay, I see. Thanks a lot!
