### ISSUE TITLE
Are there any uninstall instructions?

### ISSUE THREAD

**Issue by Mikerah** [osu-crypto/libOTe#95]
I have conflicting versions of libOTe on my system and I'm trying uninstall the one installed from this repository. However, there are no `make clean` instructions or `python build.py` command line arguments to invoke for doing that. Will I most likely need to search my system for the files associated with this repository and remove them manually?

**Comment by ladnir** [comment]
did you install it to your system or just a local build?

To get a clean build delete `out/` and the *folders* in `cryptoTools/thirdparty/` and `thirdparty/`. i.e.

```
rm -rf out/
rm -rf thirdparty/*/
rm -rf cryptoTools/thirdparty/*/
```

If you installed the library then you can find the install location delete all the files& folders there that also appear in `out/install/<platform>/` or are libOTe. For example, if you installed to `/usr/local`, then you would delete 
 * `/usr/local/include/libOTe/` 
 * `/usr/local/lib/liblibOTe.a` 
 * `/usr/local/lib/cmake/libOTe` 

To fully uninstall you also need to do this for the other dependencies that appear in `out/install/<platform>/`.

**Comment by ladnir** [comment]
Also, keep in mind that its often nice *not* to install something to the system. You can use libOTe by installing it to some custom location, maybe a subfolder of your project, or simply build libOTe and then add its location to your `CMAKE_PREFIX_PATH` variable, assuming you're using cmake.

**Comment by Mikerah** [comment]
This is what I ended up doing. Thank you very much
