### ISSUE TITLE
error: ‘asioConnect’ is not a member of ‘osuCrypto::cp’

### ISSUE THREAD

**Issue by ShallMate** [osu-crypto/libOTe#98]
I want to call Silent_example and VOLE_example. However, I found they don't seem to be compiled because COPROTO_ENABLE_BOOST and ENABLE_SILENT_VOLE. So I set COPROTO_ENABLE_BOOST=ON and ENABLE_SILENT_VOLE=ON. Meanwhile, I delete the "#if defined(ENABLE_SILENT_VOLE) && defined(COPROTO_ENABLE_BOOST)" and "#endif" at frontend/ExampleVole.h. I think this should have no effect, right? But the error in the title comes up and I don't know why.

**Comment by ladnir** [comment]
Delete the out folder and build with the full set of options

**Comment by ShallMate** [comment]
Thank you Professor, I didn't pay attention to your reply two days ago. I tried deleting the out folder and recompiling but it didn't work. I think maybe I have already installed coproto under /usr/local/include. Maybe I should recompile coproto and ask you again if I find it still doesn't work.

**Comment by ladnir** [comment]
That's right. Will be fixing this inconvenience soon

**Comment by ShallMate** [comment]
Hello professor. Sorry for the problem again, when I call Silent OT, I get a segmentation fault. Here is my code: https://github.com/ShallMate/SilentOT. I use this program like this: ./main -s -r 0 -n 1000000 and ./main -s -r 1 -n 1000000 in two terminals. But a segfault occurs and I don't know why.

**Comment by ShallMate** [comment]
`int main(int argc, char** argv){
	CLP cmd;
	cmd.parse(argc, argv);
    cout<<argv<<endl;
	cout<<argc<<endl;
    bool flagSet = false;
	flagSet |= runIf(Silent_example, cmd, Silent);
    cout<<flagSet<<endl;
	return 0;
}`
This is my main function, which I call Silent OT like this. The compilation of the code is successful, please help me take a look, thank you.

**Comment by ShallMate** [comment]
This is my main function, which I call Silent OT like this. The compilation of the code is successful, please help me take a look, thank you.
![2022-11-23 17-18-02屏幕截图](https://user-images.githubusercontent.com/25976948/203510697-71b7f344-edfe-4535-ab16-d28045fadfc7.png)

**Comment by ShallMate** [comment]
@ladnir 
Professor, I am very sorry to bother you. I tried running frontend_libOTe under /out/linux via frontend_libOTe -s -be -r 0/1 -n 1000000 and it seems to work. However, I tried to compile frontend externally again, but the segment fault still appeared.
I did not modify the code in frontend, just deleted the unit test as follows.
![2022-11-24 19-28-09屏幕截图](https://user-images.githubusercontent.com/25976948/203773433-25d03b28-80a7-44d1-9298-0d5cdacf640f.png)

I still run my externally compiled frontend with -s -r 0/1 -n 1000000 , but the segfault happens just because I compiled externally. I don't understand why, because I think the code where I removed the unit test above should have nothing to do with the segfault, so it seems like it's just because I compiled frontend externally.

Since I want to be able to use silent OT in my own program, I want to be able to solve the problem of calling silent OT externally. Here is my code about fronted: https://github.com/ShallMate/frontend. The setting of LibOte I use is -D ENABLE_RELIC=ON -D ENABLE_ALL_OT=ON -D COPROTO_ENABLE_BOOST=ON -D ENABLE_SILENT_VOLE=ON, and it has been installed locally through --install.

Thank you very much, Professor

**Comment by MingliWu** [comment]
> thank you very much. The problem has been solved, I deleted the installed coproto and recompiled it.

I get the same error even I enable all options ON (BOOST, COPROTO_ENABLE_BOOST, etc.) and recompile it. What specific options you set when you compile coproto?

**Comment by ShallMate** [comment]
@MingliWu 
Hello, I think you can try to delete the local coproto first (that is, the coproto under the thirtyparty folder and the .a and cmake related files you installed locally). Then use the following configuration: (-D ENABLE_RELIC=ON -D ENABLE_ALL_OT=ON -D COPROTO_ENABLE_BOOST=ON -D ENABLE_SILENT_VOLE=ON). I think it should work. If your problem is solved, we can discuss the segfault problem I am encountering now, if you also need to use silent OT.

**Comment by ShallMate** [comment]
@MingliWu 
Excuse me, are you Chinese? If so, I would like to add a QQ or Wechat with you because I want to talk about Silent OT.

**Comment by ladnir** [comment]
hello, currently on vacation so dont have time to look into this. One thing that would help would be to tell me where it is segfaulting. 

Also, the silent example is a bit complicated right now and I will be simplifying it in the future. 

You can also try calling it in a more straightforward way. See here for an example https://github.com/osu-crypto/libOTe/blob/master/libOTe_Tests/SilentOT_Tests.cpp#L482

**Comment by ladnir** [comment]
pushed a new silent example. Take a look and see if that helps.

**Comment by ShallMate** [comment]
Thank you professor. I will try your latest uploaded silent example and https://github.com/osu-crypto/libOTe/blob/master/libOTe_Tests/SilentOT_Tests.cpp#L482
In addition, regarding the position of the segment error, I actually tried to use gdb to locate the segment error. However, I'm not very familiar with gdb, and I get #0 0x0000000000000000 in ??() as a result. I don't know how to proceed further. All I can tell you is that the segfault is not inside the frontend. I can't find a specific question to ask you, I am sorry for this. I'll keep trying your newly uploaded example and SilentOT_Tests.cpp#L482. Due to the time difference, I often cannot reply you in time, thank you very much for your reply. Sorry for interrupting your holiday, wish you a happy holiday.

**Comment by ShallMate** [comment]
Hello Professor. I tried the new frontend with the code you provided at https://github.com/osu-crypto/libOTe/blob/master/libOTe_Tests/SilentOT_Tests.cpp#L482. Unfortunately, both methods still produce segmentation faults. But this time I managed to locate the location where the segfault occurred when using https://github.com/osu-crypto/libOTe/blob/master/libOTe_Tests/SilentOT_Tests.cpp#L482. 
The problem seems to happen at:
![2022-11-27 16-05-07屏幕截图](https://user-images.githubusercontent.com/25976948/204125207-a05c83f4-5d14-46a9-ab7f-7074b28b3033.png)
This is my gdb location information:
![2022-11-27 15-59-38屏幕截图](https://user-images.githubusercontent.com/25976948/204125216-c5fabdb7-5c74-4045-8a99-c32d0d523b69.png)
And I call Silent OT like this, which should be consistent with your calling method in https://github.com/osu-crypto/libOTe/blob/master/libOTe_Tests/SilentOT_Tests.cpp#L482.
![2022-11-27 16-00-32屏幕截图](https://user-images.githubusercontent.com/25976948/204125257-54533760-a78d-4aea-85c4-19920c8257da.png)

**Comment by ShallMate** [comment]
I use gdb and find that the segfault occurs at /usr/local/include/macoro/sync_wait.h:186
![2022-11-27 22-53-19屏幕截图](https://user-images.githubusercontent.com/25976948/204141801-e95afe65-82ef-4239-9a2d-d94bbf19388f.png)
Sorry again for disturbing the professor during the holiday, I hope you can help me to take a look at it during working hours. If it works on your side, what exactly is causing my segfault? I'm not sure if it's a bug or if I just made a mistake.

**Comment by ladnir** [comment]
First let's Uninstaller everything. 

Delete everything you see from 
* `/usr/local/include/`, 
* `/usr/local/lib`, 
* `/usr/local/lib/cmake`

That has to do with 
* macoro
* coproto
* libOTe 
* cryptoTools 
* span
* variant
* optional

Remove the `out/` folder. 

Secondly, you need to build with debug symbols. If you are using the build.py script, you can do this by adding the arguments `--debug`.

When you attach gdb now, it will give you the line number that it segfaults on.

Try running it now and if it fails attach the debugger.

**Comment by ShallMate** [comment]
I successfully ran the silent OT, I am really grateful to the professor! As you said, I deleted everything under my local /usr/local/lib and /usr/local/include. Meanwhile, I even re-clone libOTE. According to the previous build and installation method, I successfully ran the silent OT under libOTE. But to be honest, I still don't know how my previous segmentation fault was caused. Is it because I used the libOTE generated by https://github.com/Visa-Research/volepsi?

**Comment by ladnir** [comment]
Are you in debug mode?

**Comment by ShallMate** [comment]
I'm not sure. I think it may be. I added -- debug when running build. py. Does this affect efficiency?

**Comment by ladnir** [comment]
Yes, it destroys efficiency. Delete the out folder and rebuild without it

**Comment by ShallMate** [comment]
OK, Professor. I will try to delete out and recompile. Professor I have one more question, can I just delete the build and install folders in out? Or do I have to delete the whole out? Because the entire out was deleted I had to re-download the related dependencies.

**Comment by ShallMate** [comment]
Thank you very much, Professor.

**Comment by ShallMate** [comment]
The efficiency is consistent with the thesis professor, thank you very much. But when I exited the build model, the segmentation fault occurred again, and I did not make any changes to my code... But the strange thing is that the segmentation fault occurred after the sender and receiver got random OTs. Although this seems to have achieved my purpose, that is, I just want both parties to get random OTs, but I still can't understand that a segfault occurs after both parties get the output. You should know that I just ran the silent OT. Shouldn't the execution of the program end after both parties get the output? I made sure both sides got the output, I printed them to make sure the output did get.

I gradually began to suspect that it was not a problem with the code, but a problem with my CMakeLists.txt. Because the frontend generated by python3 build.py will not segfault. I have attached my CMakeLists.txt.

![2022-11-29 17-13-08屏幕截图](https://user-images.githubusercontent.com/25976948/204487837-d0d58d89-0f9d-4cd6-bf57-db78fcbac489.png)

**Comment by ladnir** [comment]
it runs correctly on my machine...

Try building libOTe with

`python3 build.py -DENABLE_ASAN=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo`.

And then rerun your code.

**Comment by ShallMate** [comment]
Professor, I ran my code again after recompiling libOTE. So the following is presented.
![2022-12-04 16-06-54屏幕截图](https://user-images.githubusercontent.com/25976948/205480652-d7db1882-adf1-44ae-aa6d-23c5c2d973a0.png)
![2022-12-04 16-07-12屏幕截图](https://user-images.githubusercontent.com/25976948/205480658-b4290ad8-f5c6-4a3c-8df9-503b3468910b.png)

**Comment by ladnir** [comment]
ok, progress... Seems it didn't build with all of the debug info (line numbers). Can you run the following in the libOTe directory? Im assuming you are on linux... If apple change `linux` to `osx`.
```
rm -rf out/
mkdir -p out/build/linux
cmake -S . -B out/build/linux  -DENABLE_ASAN=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFETCH_AUTO=ON
cmake --build out/build/linux
```

and rerun.

**Comment by ShallMate** [comment]
Professor, I recompiled libOTE this way. When compiling I use cmake .. -DCMAKE_PREFIX_PATH=../libOTe instead of installing locally, and the segfault disappeared. But I still want to install to the local, how can I install to /usr/local by this build method? Still run python build.py --install?

**Comment by ladnir** [comment]
Yeah, you should be able to call install

**Comment by ShallMate** [comment]
Thank you very much Professor. I ran cmake --install out/build/linux to complete the installation and successfully run my code without segfaulting. Thank you so much for your guidance during this time. Later, I will try to consult and read the source code of libOTE and also experience other related protocols of libOTE. Your guidance during this time has helped me strengthen my understanding of libOTE, and I would like to express my gratitude to you again.

**Comment by ladnir** [comment]
glad it worked out.
